#include "../server/sqlite_persistence.h"
#include "../server/sqlite_storage.h"
#include "../server/sha256.h"
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static unsigned char *readall(const char *p,size_t *n){FILE*f=fopen(p,"rb");long z;unsigned char*b;assert(f);fseek(f,0,SEEK_END);z=ftell(f);fseek(f,0,SEEK_SET);b=malloc((size_t)z);assert(b);assert(fread(b,1,(size_t)z,f)==(size_t)z);fclose(f);*n=(size_t)z;return b;}
static void cmd(WenaDomainCommand*c,WenaDomainOperation op,unsigned long v,const char*body){memset(c,0,sizeof(*c));c->operation=op;c->request_version=v;strcpy(c->user_id,"u1");strcpy(c->route,"/b/b1/demo");strcpy(c->form_body,body);c->form_body_length=strlen(body);}
static int count(sqlite3*d,const char*q){sqlite3_stmt*s;int n;assert(sqlite3_prepare_v2(d,q,-1,&s,NULL)==SQLITE_OK);assert(sqlite3_step(s)==SQLITE_ROW);n=sqlite3_column_int(s,0);sqlite3_finalize(s);return n;}
static void text(sqlite3*d,const char*q,char*out){sqlite3_stmt*s;assert(sqlite3_prepare_v2(d,q,-1,&s,NULL)==SQLITE_OK);assert(sqlite3_step(s)==SQLITE_ROW);strcpy(out,(const char*)sqlite3_column_text(s,0));sqlite3_finalize(s);}
int main(int ac,char**av){static const char hash[]="e4760a2b70d6651ee84dce93642ccdd4ce8991b488dece5d231e66053f065da5";unsigned char*sql;size_t n,wire_n;sqlite3*d;WenaSqlitePersistence p;WenaDomainCommand c;WenaRegionResponse r;char path[512],stored[65],actual[65],wire[WENA_REGION_RESPONSE_MAX_BYTES];assert(ac==3);sql=readall(av[1],&n);sprintf(path,"%s/db.sqlite",av[2]);assert(wena_sqlite_open(path,sql,n,hash,&d));assert(sqlite3_exec(d,"INSERT INTO actors VALUES('u1','User',1);INSERT INTO boards VALUES('b1','Board',1);INSERT INTO swimlanes VALUES('s1','b1','Lane',0,1);INSERT INTO lists VALUES('l1','b1','List',0,1);",NULL,NULL,NULL)==SQLITE_OK);wena_sqlite_persistence_init(&p,d);
cmd(&c,WENA_DOMAIN_CREATE_CARD,1,"title=First");assert(wena_sqlite_persistence_apply(&p,&c,&r));assert(count(d,"SELECT count(*) FROM cards")==1);assert(wena_region_response_encode(&r,wire,sizeof(wire),&wire_n));wena_sha256_hex((const unsigned char*)wire,wire_n,actual);text(d,"SELECT response_checksum FROM idempotency_keys",stored);assert(strcmp(stored,actual)==0);assert(!wena_sqlite_persistence_apply(&p,&c,&r));assert(count(d,"SELECT count(*) FROM cards")==1);
cmd(&c,WENA_DOMAIN_CREATE_CARD,2,"title=Forbidden");strcpy(c.user_id,"other");assert(!wena_sqlite_persistence_apply(&p,&c,&r));strcpy(c.user_id,"u1");strcpy(c.route,"/b/missing/demo");assert(!wena_sqlite_persistence_apply(&p,&c,&r));assert(count(d,"SELECT count(*) FROM cards")==1);
cmd(&c,WENA_DOMAIN_EDIT_CARD_TITLE,2,"cardId=card-1&expectedVersion=9&title=Bad");assert(!wena_sqlite_persistence_apply(&p,&c,&r));assert(count(d,"SELECT count(*) FROM idempotency_keys")==1);cmd(&c,WENA_DOMAIN_EDIT_CARD_TITLE,2,"cardId=card-1&expectedVersion=1&title=Second");assert(wena_sqlite_persistence_apply(&p,&c,&r));
cmd(&c,WENA_DOMAIN_ARCHIVE_CARD,3,"cardId=card-1&expectedVersion=2");assert(wena_sqlite_persistence_apply(&p,&c,&r));
cmd(&c,WENA_DOMAIN_EDIT_BOARD_TITLE,4,"expectedVersion=9&title=Wrong");assert(!wena_sqlite_persistence_apply(&p,&c,&r));assert(count(d,"SELECT version FROM boards WHERE id='b1'")==1);assert(count(d,"SELECT count(*) FROM idempotency_keys")==3);
cmd(&c,WENA_DOMAIN_EDIT_BOARD_TITLE,4,"expectedVersion=1&title=Renamed");assert(wena_sqlite_persistence_apply(&p,&c,&r));assert(count(d,"SELECT version FROM boards WHERE id='b1'")==2);assert(!wena_sqlite_persistence_apply(&p,&c,&r));
cmd(&c,WENA_DOMAIN_EDIT_BOARD_TITLE,5,"expectedVersion=2&title=Forbidden");strcpy(c.user_id,"other");assert(!wena_sqlite_persistence_apply(&p,&c,&r));strcpy(c.user_id,"u1");strcpy(c.route,"/b/missing/demo");assert(!wena_sqlite_persistence_apply(&p,&c,&r));assert(count(d,"SELECT version FROM boards WHERE id='b1'")==2);
cmd(&c,WENA_DOMAIN_EDIT_LIST_TITLE,5,"listId=l1&expectedVersion=9&title=Wrong");strcpy(c.route,"/b/b1/demo");assert(!wena_sqlite_persistence_apply(&p,&c,&r));assert(count(d,"SELECT version FROM lists WHERE id='l1'")==1);
cmd(&c,WENA_DOMAIN_EDIT_LIST_TITLE,5,"listId=l1&expectedVersion=1&title=Renamed List");assert(wena_sqlite_persistence_apply(&p,&c,&r));assert(count(d,"SELECT version FROM lists WHERE id='l1'")==2);assert(!wena_sqlite_persistence_apply(&p,&c,&r));
cmd(&c,WENA_DOMAIN_EDIT_LIST_TITLE,6,"listId=l1&expectedVersion=2&title=Cross Board");strcpy(c.route,"/b/missing/demo");assert(!wena_sqlite_persistence_apply(&p,&c,&r));assert(count(d,"SELECT version FROM lists WHERE id='l1'")==2);
cmd(&c,WENA_DOMAIN_EDIT_SWIMLANE_TITLE,6,"swimlaneId=s1&expectedVersion=9&title=Wrong");strcpy(c.route,"/b/b1/demo");assert(!wena_sqlite_persistence_apply(&p,&c,&r));assert(count(d,"SELECT version FROM swimlanes WHERE id='s1'")==1);
cmd(&c,WENA_DOMAIN_EDIT_SWIMLANE_TITLE,6,"swimlaneId=s1&expectedVersion=1&title=Renamed Lane");assert(wena_sqlite_persistence_apply(&p,&c,&r));assert(count(d,"SELECT version FROM swimlanes WHERE id='s1'")==2);assert(!wena_sqlite_persistence_apply(&p,&c,&r));
cmd(&c,WENA_DOMAIN_EDIT_SWIMLANE_TITLE,7,"swimlaneId=s1&expectedVersion=2&title=Cross Board");strcpy(c.route,"/b/missing/demo");assert(!wena_sqlite_persistence_apply(&p,&c,&r));assert(count(d,"SELECT version FROM swimlanes WHERE id='s1'")==2);
sqlite3_close(d);assert(wena_sqlite_open(path,sql,n,hash,&d));assert(count(d,"SELECT archived FROM cards WHERE id='card-1'")==1);assert(count(d,"SELECT version FROM boards WHERE id='b1'")==2);assert(count(d,"SELECT version FROM lists WHERE id='l1'")==2);assert(count(d,"SELECT version FROM swimlanes WHERE id='s1'")==2);assert(count(d,"SELECT count(*) FROM idempotency_keys")==6);sqlite3_close(d);free(sql);return 0;}
