/* SPDX-License-Identifier: MIT. Generated by scripts/compile_svg.py. */
static const WenaSvgShape wena_board_svg_shapes[] = {
    {1,{2.0f,3.0f,20.0f,18.0f,2.0f},-1L,-2L,1.5f},
    {1,{5.0f,6.0f,3.0f,9.0f,0.0f},-2L,-1L,1.0f},
    {1,{10.5f,6.0f,3.0f,12.0f,0.0f},-2L,-1L,1.0f},
    {1,{16.0f,6.0f,3.0f,6.0f,0.0f},-2L,-1L,1.0f},
};
static const WenaSvgAsset wena_board_svg = {24.0f,24.0f,4u,wena_board_svg_shapes};
