#ifndef WENA_UI_PAGE_CONTRACT_H
#define WENA_UI_PAGE_CONTRACT_H

#include <stddef.h>
#include "../../models/color.h"

#define WENA_UI_BASELINE_CONTENT_TABLES 1u
#define WENA_UI_NATURAL_TAB_ORDER 1u

typedef enum WenaUiControlId {
    WENA_UI_BOARD_MENU,
    WENA_UI_ADD_CARD,
    WENA_UI_LIST_MENU,
    WENA_UI_OPEN_CARD,
    WENA_UI_CARD_MENU,
    WENA_UI_EDIT_TITLE,
    WENA_UI_ARCHIVE_CARD,
    WENA_UI_CLOSE,
    WENA_UI_MOVE_CARD,
    WENA_UI_MOVE_LIST,
    WENA_UI_MOVE_SWIMLANE,
    WENA_UI_SAVE,
    WENA_UI_CANCEL,
    WENA_UI_COLLAPSE_LIST,
    WENA_UI_EXPAND_LIST,
    WENA_UI_COLLAPSE_SWIMLANE,
    WENA_UI_EXPAND_SWIMLANE,
    WENA_UI_MOVE_CARD_TO,
    WENA_UI_ADD_LIST,
    WENA_UI_ADD_SWIMLANE,
    WENA_UI_RENAME_BOARD,
    WENA_UI_RENAME_SWIMLANE,
    WENA_UI_RESTORE_CARD,
    WENA_UI_MOVE_LIST_TO,
    WENA_UI_MOVE_SWIMLANE_TO,
    WENA_UI_EDIT_DESCRIPTION,
    WENA_UI_OPEN_CHECKLISTS,
    WENA_UI_ADD_CHECKLIST,
    WENA_UI_ADD_CHECKLIST_ITEM,
    WENA_UI_RENAME_CHECKLIST,
    WENA_UI_RENAME_CHECKLIST_ITEM,
    WENA_UI_CHECKLIST_SETTINGS,
    WENA_UI_OPEN_DELETE_CHECKLIST,
    WENA_UI_OPEN_DELETE_CHECKLIST_ITEM,
    WENA_UI_CONFIRM_DELETE,
    WENA_UI_OPEN_LABELS,
    WENA_UI_ADD_LABEL,
    WENA_UI_EDIT_LABEL,
    WENA_UI_OPEN_DELETE_LABEL,
    WENA_UI_CREATE_LABEL,
    WENA_UI_ARCHIVE_LIST,
    WENA_UI_ARCHIVE_SWIMLANE
} WenaUiControlId;

typedef struct WenaUiControlContract {
    WenaUiControlId id;
    const char *i18n_key;
    const char *fallback_text;
    const char *ascii_control;
    const char *http_method;
    const char *domain_operation;
    unsigned int tab_order;
} WenaUiControlContract;

typedef struct WenaUiPageContract {
    const char *route_family;
    const char *heading_i18n_key;
} WenaUiPageContract;

typedef WenaColorContract WenaUiColorContract;

typedef enum WenaUiTextId {
    WENA_UI_TEXT_ACTIVITIES,
    WENA_UI_TEXT_MEMBERS,
    WENA_UI_TEXT_LABELS,
    WENA_UI_TEXT_ARCHIVES,
    WENA_UI_TEXT_REFRESH,
    WENA_UI_TEXT_ADD_MEMBER,
    WENA_UI_TEXT_ADD_LABEL,
    WENA_UI_TEXT_REMOVE_LABEL,
    WENA_UI_TEXT_RESTORE,
    WENA_UI_TEXT_LANGUAGE,
    WENA_UI_TEXT_SWIMLANE,
    WENA_UI_TEXT_LIST,
    WENA_UI_TEXT_NO_ARCHIVED_CARDS,
    WENA_UI_TEXT_ERROR,
    WENA_UI_TEXT_OPERATION_FAILED,
    WENA_UI_TEXT_NO_ITEMS,
    WENA_UI_TEXT_UNKNOWN,
    WENA_UI_TEXT_CARD_DETAILS,
    WENA_UI_TEXT_MANUAL_ORDER,
    WENA_UI_TEXT_MOVE_TO_BOTTOM,
    WENA_UI_TEXT_ARCHIVED,
    WENA_UI_TEXT_DESCRIPTION,
    WENA_UI_TEXT_CHECKLISTS,
    WENA_UI_TEXT_CHECKLIST,
    WENA_UI_TEXT_CHECKLIST_COUNT,
    WENA_UI_TEXT_COMPLETE,
    WENA_UI_TEXT_FILTER,
    WENA_UI_TEXT_FILTER_CARD_TITLE,
    WENA_UI_TEXT_FILTER_CLEAR,
    WENA_UI_TEXT_NO_CARDS_FOUND,
    WENA_UI_TEXT_HIDE_CHECKED_ITEMS,
    WENA_UI_TEXT_HIDE_ALL_ITEMS,
    WENA_UI_TEXT_SHOW_ON_MINICARD,
    WENA_UI_TEXT_DEFAULT,
    WENA_UI_TEXT_YES,
    WENA_UI_TEXT_NO,
    WENA_UI_TEXT_SETTINGS,
    WENA_UI_TEXT_DELETE_CHECKLIST,
    WENA_UI_TEXT_DELETE_CHECKLIST_ITEM,
    WENA_UI_TEXT_CONFIRM_DELETE_CHECKLIST,
    WENA_UI_TEXT_CONFIRM_DELETE_CHECKLIST_ITEM,
    WENA_UI_TEXT_CHECKLIST_WITH_ITEMS,
    WENA_UI_TEXT_NAME,
    WENA_UI_TEXT_SELECT_COLOR,
    WENA_UI_TEXT_CUSTOM_COLOR,
    WENA_UI_TEXT_CREATE_LABEL,
    WENA_UI_TEXT_EDIT_LABEL,
    WENA_UI_TEXT_DELETE_LABEL,
    WENA_UI_TEXT_CARDS,
    WENA_UI_TEXT_CHECKLIST_SPLIT_LINES,
    WENA_UI_TEXT_CHECKLIST_COUNT_ON_MINICARD,
    WENA_UI_TEXT_MOVE_SELECTION,
    WENA_UI_TEXT_MOVE_CHECKLIST,
    WENA_UI_TEXT_MOVE_DESTINATION,
    WENA_UI_TEXT_PREVIOUS_PAGE,
    WENA_UI_TEXT_NEXT_PAGE,
    WENA_UI_TEXT_LOADING,
    WENA_UI_TEXT_BOARDS,
    WENA_UI_TEXT_LISTS,
    WENA_UI_TEXT_NO_ARCHIVED_LISTS,
    WENA_UI_TEXT_SWIMLANES,
    WENA_UI_TEXT_NO_ARCHIVED_SWIMLANES,
    WENA_UI_TEXT_EDIT_WIP_LIMIT,
    WENA_UI_TEXT_ENABLE_WIP_LIMIT,
    WENA_UI_TEXT_SOFT_WIP_LIMIT,
    WENA_UI_TEXT_ARCHIVE_LIST_CARDS,
    WENA_UI_TEXT_ARCHIVE_LIST_CARDS_CONFIRM,
    WENA_UI_TEXT_MOVE_TO_ARCHIVE,
    WENA_UI_TEXT_MULTI_SELECTION,
    WENA_UI_TEXT_MULTI_SELECTION_OFF,
    WENA_UI_TEXT_SELECT_ALL,
    WENA_UI_TEXT_SELECT_NONE,
    WENA_UI_TEXT_SELECT_LIST_CARDS,
    WENA_UI_TEXT_SELECTED,
    WENA_UI_TEXT_ARCHIVE_SELECTION
} WenaUiTextId;

/* The renderer owns this process-local callback and its context lifetime.
 * Returned strings must remain alive through the rendered frame. NULL resets
 * the adapter; unknown translations fall back to the existing UI contract. */
typedef const char *(*WenaUiTranslator)(void *context, const char *key);
void wena_ui_set_translator(WenaUiTranslator translator, void *context);
const char *wena_ui_text(WenaUiTextId id);

const WenaUiControlContract *wena_ui_control(WenaUiControlId id);
const char *wena_ui_control_text(WenaUiControlId id);
const WenaUiPageContract *wena_ui_pages(size_t *count);
const WenaUiColorContract *wena_ui_colors(size_t *count);

#endif
