#include "sqlite_restore.h"
#include "sha256.h"
#include "sqlite_storage.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define PATH_MAXIMUM 1024
#define COPY_MARGIN 1048576ul
static int hash_file(const char*p,char out[65],unsigned long*size){FILE*f;unsigned char b[16384];size_t n;WenaSha256 s;unsigned long z=0;f=fopen(p,"rb");if(!f)return 0;wena_sha256_init(&s);while((n=fread(b,1,sizeof(b),f))>0){if(z>(unsigned long)-1-(unsigned long)n){fclose(f);return 0;}z+=(unsigned long)n;wena_sha256_update(&s,b,n);}if(ferror(f)||fclose(f)!=0)return 0;wena_sha256_final_hex(&s,out);*size=z;return 1;}
static int sidecar(const char*p,const char*hash){char q[PATH_MAXIMUM],line[67];FILE*f;size_t n;sprintf(q,"%s.sha256",p);f=fopen(q,"rb");if(!f)return 0;n=fread(line,1,sizeof(line),f);if(ferror(f)){fclose(f);return 0;}fclose(f);return n==65u&&line[64]=='\n'&&memcmp(line,hash,64)==0;}
static int scalar_text(sqlite3*d,const char*q,const char*expected){sqlite3_stmt*s;int ok;if(sqlite3_prepare_v2(d,q,-1,&s,NULL)!=SQLITE_OK)return 0;ok=sqlite3_step(s)==SQLITE_ROW&&sqlite3_column_text(s,0)&&strcmp((const char*)sqlite3_column_text(s,0),expected)==0;sqlite3_finalize(s);return ok;}
static int preflight(const char*p,const char*migration,unsigned long*size){sqlite3*d=NULL;sqlite3_stmt*s;int v=-1;char hash[65];if(!hash_file(p,hash,size)||!sidecar(p,hash))return 0;if(sqlite3_open_v2(p,&d,SQLITE_OPEN_READONLY|SQLITE_OPEN_FULLMUTEX,NULL)!=SQLITE_OK)goto bad;if(!wena_sqlite_integrity(d)||sqlite3_prepare_v2(d,"PRAGMA user_version",-1,&s,NULL)!=SQLITE_OK)goto bad;if(sqlite3_step(s)==SQLITE_ROW)v=sqlite3_column_int(s,0);sqlite3_finalize(s);if(v!=1||!scalar_text(d,"SELECT checksum FROM schema_migrations WHERE version=1",migration))goto bad;sqlite3_close(d);return 1;bad:if(d)sqlite3_close(d);return 0;}
static int copy_file(const char*a,const char*b){FILE*i,*o;unsigned char p[16384];size_t n;i=fopen(a,"rb");if(!i)return 0;o=fopen(b,"wb");if(!o){fclose(i);return 0;}while((n=fread(p,1,sizeof(p),i))>0)if(fwrite(p,1,n,o)!=n){fclose(i);fclose(o);return 0;}if(ferror(i)||fflush(o)!=0||fclose(o)!=0){fclose(i);return 0;}return fclose(i)==0;}
static int exists(const char*p){FILE*f=fopen(p,"rb");if(!f)return 0;fclose(f);return 1;}
int wena_sqlite_restore(const char*backup,const char*database,const char*migration,WenaBackupFreeSpace free_space,void*space_context,const WenaRestoreLifecycle*lifecycle){char temporary[PATH_MAXIMUM],original[PATH_MAXIMUM];unsigned long size,available;if(!backup||!database||!migration||!free_space||!lifecycle||!lifecycle->stop||!lifecycle->start||backup[0]!='/'||database[0]!='/'||strlen(backup)>PATH_MAXIMUM-16u||strlen(database)>PATH_MAXIMUM-24u)return 0;sprintf(temporary,"%s.restore.tmp",database);sprintf(original,"%s.restore-original",database);if(exists(temporary)||exists(original)||!exists(database)||!preflight(backup,migration,&size))return 0;if(size>(unsigned long)-1-COPY_MARGIN||!free_space(space_context,database,&available)||available<size+COPY_MARGIN)return 0;if(!copy_file(backup,temporary)){remove(temporary);return 0;}if(!lifecycle->stop(lifecycle->context)){remove(temporary);return 0;}if(rename(database,original)!=0){remove(temporary);lifecycle->start(lifecycle->context,database);return 0;}if(rename(temporary,database)!=0){rename(original,database);lifecycle->start(lifecycle->context,database);remove(temporary);return 0;}if(lifecycle->start(lifecycle->context,database)){remove(original);return 1;}remove(database);if(rename(original,database)==0)lifecycle->start(lifecycle->context,database);return 0;}
