#include "sqlite_persistence.h"
#include "sha256.h"
#include <stdio.h>
#include <string.h>

static int value(const WenaDomainCommand *c,const char *name,char *out,size_t cap){size_t p=0;int found=0;while(p<c->form_body_length){size_t e=p,q,l;e=p;while(e<c->form_body_length&&c->form_body[e]!='&')e++;q=p;while(q<e&&c->form_body[q]!='=')q++;if(q==e)return 0;if(q-p==strlen(name)&&memcmp(c->form_body+p,name,q-p)==0){if(found)return 0;l=e-q-1;if(!l||l>=cap)return 0;memcpy(out,c->form_body+q+1,l);out[l]=0;found=1;}p=e+1;}return found;}
static int scalar(sqlite3 *db,const char *sql,const char *a,const char *b,const char *c,unsigned long n){sqlite3_stmt *s;int ok;if(sqlite3_prepare_v2(db,sql,-1,&s,NULL)!=SQLITE_OK)return 0;if(a)sqlite3_bind_text(s,1,a,-1,SQLITE_TRANSIENT);if(b)sqlite3_bind_text(s,2,b,-1,SQLITE_TRANSIENT);if(c)sqlite3_bind_text(s,3,c,-1,SQLITE_TRANSIENT);if(n)sqlite3_bind_int64(s,4,(sqlite3_int64)n);ok=sqlite3_step(s)==SQLITE_ROW&&sqlite3_column_int(s,0)>0;sqlite3_finalize(s);return ok;}
static int board_id(const char *route,char *out){const char *end;if(strncmp(route,"/b/",3)!=0)return 0;end=strchr(route+3,'/');if(!end||end==route+3||(size_t)(end-route-3)>=65)return 0;memcpy(out,route+3,(size_t)(end-route-3));out[end-route-3]=0;return 1;}
static int run(sqlite3 *db,const char *sql,const char *a,const char *b,const char *c,unsigned long n){sqlite3_stmt *s;int ok;if(sqlite3_prepare_v2(db,sql,-1,&s,NULL)!=SQLITE_OK)return 0;if(a)sqlite3_bind_text(s,1,a,-1,SQLITE_TRANSIENT);if(b)sqlite3_bind_text(s,2,b,-1,SQLITE_TRANSIENT);if(c)sqlite3_bind_text(s,3,c,-1,SQLITE_TRANSIENT);if(n)sqlite3_bind_int64(s,4,(sqlite3_int64)n);ok=sqlite3_step(s)==SQLITE_DONE&&sqlite3_changes(db)==1;sqlite3_finalize(s);return ok;}
static int move_card(sqlite3*d,const char*list,const char*lane,const char*id,const char*board,unsigned long version){sqlite3_stmt*s;int ok;const char*q="UPDATE cards SET list_id=?1,swimlane_id=?2,position=COALESCE((SELECT max(position)+1 FROM cards c2 WHERE c2.list_id=?1 AND c2.swimlane_id=?2),0),version=version+1 WHERE id=?3 AND board_id=?4 AND version=?5 AND archived=0";if(sqlite3_prepare_v2(d,q,-1,&s,NULL)!=SQLITE_OK)return 0;sqlite3_bind_text(s,1,list,-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,2,lane,-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,3,id,-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,4,board,-1,SQLITE_TRANSIENT);sqlite3_bind_int64(s,5,(sqlite3_int64)version);ok=sqlite3_step(s)==SQLITE_DONE&&sqlite3_changes(d)==1;sqlite3_finalize(s);return ok;}
static int checksum(sqlite3 *db,const char *wire,size_t length){sqlite3_stmt*s;char hash[65];int ok;wena_sha256_hex((const unsigned char *)wire,length,hash);if(sqlite3_prepare_v2(db,"UPDATE idempotency_keys SET response_checksum=?1 WHERE response_checksum='pending'",-1,&s,NULL)!=SQLITE_OK)return 0;sqlite3_bind_text(s,1,hash,-1,SQLITE_TRANSIENT);ok=sqlite3_step(s)==SQLITE_DONE&&sqlite3_changes(db)==1;sqlite3_finalize(s);return ok;}
static const char *operation_name(WenaDomainOperation operation){if(operation==WENA_DOMAIN_CREATE_CARD)return "create-card";if(operation==WENA_DOMAIN_EDIT_CARD_TITLE)return "edit-card-title";if(operation==WENA_DOMAIN_ARCHIVE_CARD)return "archive-card";if(operation==WENA_DOMAIN_EDIT_BOARD_TITLE)return "edit-board-title";if(operation==WENA_DOMAIN_EDIT_LIST_TITLE)return "edit-list-title";if(operation==WENA_DOMAIN_EDIT_SWIMLANE_TITLE)return "edit-swimlane-title";if(operation==WENA_DOMAIN_MOVE_CARD)return "move-card";return NULL;}
void wena_sqlite_persistence_init(WenaSqlitePersistence *s,sqlite3 *db){if(s)s->database=db;}
int wena_sqlite_persistence_apply(void *context,const WenaDomainCommand *c,WenaRegionResponse *r){WenaSqlitePersistence *s=(WenaSqlitePersistence *)context;sqlite3 *db;char board[65],id[65],title[129],expected[32],wire[WENA_REGION_RESPONSE_MAX_BYTES];const char*op;size_t wire_len;unsigned long version;if(!s||!(db=s->database)||!c||!r||!board_id(c->route,board)||(op=operation_name(c->operation))==NULL)return 0;memset(r,0,sizeof(*r));if(sqlite3_exec(db,"BEGIN IMMEDIATE",NULL,NULL,NULL)!=SQLITE_OK)return 0;if(!scalar(db,"SELECT count(*) FROM actors WHERE id=?1",c->user_id,NULL,NULL,0)||scalar(db,"SELECT count(*) FROM idempotency_keys WHERE actor_id=?1 AND route=?2 AND operation=?3 AND request_version=?4",c->user_id,c->route,op,c->request_version))goto bad;
if(c->operation==WENA_DOMAIN_CREATE_CARD){if(!value(c,"title",title,sizeof(title)))goto bad;sprintf(id,"card-%lu",c->request_version);if(!run(db,"INSERT INTO cards(id,board_id,swimlane_id,list_id,title,position,version) SELECT ?1,?2,s.id,l.id,?3,COALESCE((SELECT max(position)+1 FROM cards WHERE list_id=l.id AND swimlane_id=s.id),0),1 FROM swimlanes s,lists l WHERE s.board_id=?2 AND l.board_id=?2 ORDER BY s.position,l.position LIMIT 1",id,board,title,0))goto bad;version=1;
}else if(c->operation==WENA_DOMAIN_EDIT_BOARD_TITLE){if(!value(c,"title",title,sizeof(title))||!value(c,"expectedVersion",expected,sizeof(expected))||sscanf(expected,"%lu",&version)!=1||!run(db,"UPDATE boards SET title=?1,version=version+1 WHERE id=?2 AND id=?3 AND version=?4",title,board,board,version))goto bad;version++;
}else if(c->operation==WENA_DOMAIN_EDIT_LIST_TITLE){if(!value(c,"listId",id,sizeof(id))||!value(c,"title",title,sizeof(title))||!value(c,"expectedVersion",expected,sizeof(expected))||sscanf(expected,"%lu",&version)!=1||!run(db,"UPDATE lists SET title=?1,version=version+1 WHERE id=?2 AND board_id=?3 AND version=?4",title,id,board,version))goto bad;version++;
}else if(c->operation==WENA_DOMAIN_EDIT_SWIMLANE_TITLE){if(!value(c,"swimlaneId",id,sizeof(id))||!value(c,"title",title,sizeof(title))||!value(c,"expectedVersion",expected,sizeof(expected))||sscanf(expected,"%lu",&version)!=1||!run(db,"UPDATE swimlanes SET title=?1,version=version+1 WHERE id=?2 AND board_id=?3 AND version=?4",title,id,board,version))goto bad;version++;
}else if(c->operation==WENA_DOMAIN_MOVE_CARD){char list[65],lane[65];if(!value(c,"cardId",id,sizeof(id))||!value(c,"targetListId",list,sizeof(list))||!value(c,"targetSwimlaneId",lane,sizeof(lane))||!value(c,"expectedVersion",expected,sizeof(expected))||sscanf(expected,"%lu",&version)!=1)goto bad;if(!scalar(db,"SELECT count(*) FROM lists WHERE id=?1 AND board_id=?2",list,board,NULL,0)||!scalar(db,"SELECT count(*) FROM swimlanes WHERE id=?1 AND board_id=?2",lane,board,NULL,0)||!move_card(db,list,lane,id,board,version))goto bad;strcpy(title,"Moved");version++;
}else{if(!value(c,"cardId",id,sizeof(id))||!value(c,"expectedVersion",expected,sizeof(expected))||sscanf(expected,"%lu",&version)!=1)goto bad;if(c->operation==WENA_DOMAIN_EDIT_CARD_TITLE){if(!value(c,"title",title,sizeof(title))||!run(db,"UPDATE cards SET title=?1,version=version+1 WHERE id=?2 AND board_id=?3 AND version=?4 AND archived=0",title,id,board,version))goto bad;}else if(c->operation==WENA_DOMAIN_ARCHIVE_CARD){strcpy(title,"Archived");if(!run(db,"UPDATE cards SET archived=1,version=version+1 WHERE id=?1 AND board_id=?2 AND version=?4 AND archived=0",id,board,NULL,version))goto bad;}else goto bad;version++;}
r->request_version=c->request_version;r->region_count=1;strcpy(r->regions[0].name,"board");r->regions[0].version=version;strcpy(r->regions[0].content,title);r->regions[0].content_length=strlen(title);if(!wena_region_response_encode(r,wire,sizeof(wire),&wire_len))goto bad;if(!run(db,"INSERT INTO idempotency_keys(actor_id,route,operation,request_version,response_checksum,committed_at) VALUES(?1,?2,?3,?4,'pending',strftime('%s','now'))",c->user_id,c->route,op,c->request_version)||!checksum(db,wire,wire_len))goto bad;if(sqlite3_exec(db,"COMMIT",NULL,NULL,NULL)!=SQLITE_OK)goto bad;return 1;bad:sqlite3_exec(db,"ROLLBACK",NULL,NULL,NULL);memset(r,0,sizeof(*r));return 0;}
