#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Compile Wena's trusted SVG artwork to bounded C89 vector commands.

Python standard library only. Reject unsupported SVG rather than approximating
it silently. The runtime draws vectors at the requested size and theme color;
no XML parser, raster size variants, external resource loader or font is embedded.
"""
import argparse
import math
from pathlib import Path
import re
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
SVG = '{http://www.w3.org/2000/svg}'
MAX_BYTES = 65536
MAX_SHAPES = 128
COLORS = {'none': -1, 'currentColor': -2}


def number(value):
    if not re.fullmatch(r'-?(?:[0-9]+(?:\.[0-9]*)?|\.[0-9]+)', value):
        raise ValueError('unsupported SVG number')
    n = float(value)
    if not math.isfinite(n) or abs(n) > 4096:
        raise ValueError('SVG coordinate out of bounds')
    return n


def color(value):
    if value in COLORS:
        return COLORS[value]
    if not re.fullmatch(r'#[0-9a-fA-F]{6}', value):
        raise ValueError('only solid RGB or currentColor paints are supported')
    return int(value[1:], 16)


def parse(data):
    if len(data) > MAX_BYTES or b'<!' in data.replace(b'<!--', b''):
        raise ValueError('oversized SVG or unsupported declaration')
    root = ET.fromstring(data)
    if root.tag != SVG + 'svg' or set(root.attrib) != {'viewBox'} or (root.text or '').strip():
        raise ValueError('expected a plain SVG viewBox')
    view = [number(v) for v in root.attrib['viewBox'].split()]
    if len(view) != 4 or view[:2] != [0, 0] or min(view[2:]) <= 0:
        raise ValueError('expected positive zero-origin viewBox')
    shapes = []
    for node in root:
        if len(node) or (node.text or '').strip() or (node.tail or '').strip():
            raise ValueError('nested SVG/text is unsupported')
        kind = node.tag.removeprefix(SVG)
        geometry = {'rect': {'x','y','width','height','rx'},
                    'circle': {'cx','cy','r'}, 'line': {'x1','y1','x2','y2'}}
        if node.tag != SVG + kind or kind not in geometry:
            raise ValueError('unsupported SVG element')
        allowed = geometry[kind] | {'fill','stroke','stroke-width','id','data-color'}
        if set(node.attrib) - allowed:
            raise ValueError('unsupported SVG attribute')
        fill = color(node.get('fill', '#000000'))
        stroke = color(node.get('stroke', 'none'))
        width = number(node.get('stroke-width', '1'))
        if width <= 0:
            raise ValueError('invalid stroke width')
        if kind == 'rect':
            values = [number(node.get(k, '0')) for k in ('x','y','width','height','rx')]
            x, y, w, h, radius = values
            if min(w, h) <= 0 or radius < 0 or radius > min(w, h) / 2:
                raise ValueError('invalid rectangle')
            bounds = x, y, x+w, y+h
        elif kind == 'circle':
            x,y,r = [number(node.get(k, '0')) for k in ('cx','cy','r')]
            if r <= 0:
                raise ValueError('invalid circle')
            values = [x-r,y-r,2*r,2*r,0]
            bounds = x-r,y-r,x+r,y+r
        else:
            values = [number(node.get(k, '0')) for k in ('x1','y1','x2','y2')] + [0]
            fill = -1
            bounds = min(values[0],values[2]),min(values[1],values[3]),max(values[0],values[2]),max(values[1],values[3])
        if min(bounds[:2]) < 0 or bounds[2] > view[2] or bounds[3] > view[3]:
            raise ValueError('geometry outside viewBox')
        # Stroke must fit too; no SVG clipPath support is claimed.
        if stroke != -1 and (min(bounds[:2]) < width/2 or
                bounds[2]+width/2 > view[2] or bounds[3]+width/2 > view[3]):
            raise ValueError('stroke outside viewBox')
        shapes.append((kind, values, fill, stroke, width, node.attrib))
    if not shapes or len(shapes) > MAX_SHAPES:
        raise ValueError('invalid SVG shape count')
    return view[2:], shapes


def cf(value):
    return format(value, '.8g') + ('.0f' if value == int(value) else 'f')


def generate():
    if {p.name for p in (ROOT/'imports/ui/svg').glob('*.svg')} != {'board.svg','native-light.svg'}:
        raise ValueError('update the conversion catalog for every new SVG source')
    size, shapes = parse((ROOT/'imports/ui/svg/board.svg').read_bytes())
    out = '/* SPDX-License-Identifier: MIT. Generated by scripts/compile_svg.py. */\n'
    out += 'static const WenaSvgShape wena_board_svg_shapes[] = {\n'
    kinds = {'rect': 1, 'circle': 2, 'line': 3}
    for kind, values, fill, stroke, width, _ in shapes:
        out += '    {%d,{%s},%dL,%dL,%s},\n' % (kinds[kind], ','.join(map(cf, values)), fill, stroke, cf(width))
    out += '};\nstatic const WenaSvgAsset wena_board_svg = {%s,%s,%du,wena_board_svg_shapes};\n' % (cf(size[0]), cf(size[1]), len(shapes))
    _, tokens = parse((ROOT/'imports/ui/svg/native-light.svg').read_bytes())
    canonical = dict(re.findall(r'\{"([a-z]+)", "(#[0-9a-f]{6})"\}', (ROOT/'models/color.c').read_text()))
    theme = '/* SPDX-License-Identifier: MIT. Generated from native-light.svg. */\n'
    expected = {'accent','ink','paper','panel','navy','border','window-padding','group-padding','spacing','button-padding'}
    found = set()
    for kind, values, fill, stroke, _, attrs in tokens:
        name = attrs.get('id')
        if name not in expected or name in found or kind != 'rect' or stroke != -1:
            raise ValueError('unexpected native theme token')
        found.add(name)
        prefix = 'WENA_SVG_THEME_' + name.upper().replace('-', '_')
        if ('data-color' in attrs) != (name in {'accent','ink','paper','panel','navy','border'}):
            raise ValueError('wrong theme token kind')
        if 'data-color' in attrs:
            source = attrs['data-color']
            if source not in canonical or fill != color(canonical[source]):
                raise ValueError('theme swatch differs from canonical color')
            theme += '#define %s "%s"\n' % (prefix, source)
        else:
            if fill != -1:
                raise ValueError('measurement token must be invisible')
            theme += '#define %s_X %s\n#define %s_Y %s\n' % (prefix, cf(values[2]), prefix, cf(values[3]))
    if found != expected:
        raise ValueError('missing native theme token')
    return {'client/platform/svg_data.h': out, 'client/platform/svg_theme_data.h': theme}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for name, output in generate().items():
        path = ROOT/name
        if args.check:
            if path.read_text() != output:
                raise SystemExit('stale SVG conversion: ' + name)
        else:
            path.write_text(output)
    print('SVG vector commands and canonical theme tokens verified')

if __name__ == '__main__':
    main()
