#!/usr/bin/env python3
"""Compile the files a native test reads into the test itself.

    embed_test_files.py OUTPUT_HEADER FILE...

Writes OUTPUT_HEADER (wena_test_files.h, for tests/support/test_files.c) with
each FILE's bytes as a constant array, named by the file's last path
component. A test then gets its schema and fixture SQL from the program, never
from a path read at run time, so no SQL a test executes comes from outside
it (CodeQL cpp/sql-injection). Two files with the same name are refused.
"""

from pathlib import Path
import sys


def header(paths):
    names = [Path(path).name for path in paths]
    if len(set(names)) != len(names):
        raise ValueError("two embedded files share a name: " + ", ".join(sorted(names)))
    lines = ["/* Generated by scripts/embed_test_files.py; do not edit. */"]
    for index, path in enumerate(paths):
        data = Path(path).read_bytes() + b"\0"
        body = ",".join(str(byte) for byte in data)
        lines.append(f"static const unsigned char wena_test_file_{index}[] = {{{body}}};")
    entries = ",".join(f'{{"{names[i]}",wena_test_file_{i},{len(Path(p).read_bytes())}u}}'
                       for i, p in enumerate(paths))
    lines.append(f"static const WenaTestFile wena_test_files[] = {{{entries or '{0,0,0u}'}}};")
    lines.append(f"#define WENA_TEST_FILE_COUNT {len(paths)}u")
    return "\n".join(lines) + "\n"


def main(argv):
    if len(argv) < 1:
        print("Usage: embed_test_files.py OUTPUT_HEADER FILE...", file=sys.stderr)
        return 2
    try:
        Path(argv[0]).write_text(header(argv[1:]), encoding="ascii")
    except (OSError, ValueError) as error:
        print(f"embed_test_files: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
