#!/usr/bin/env python3
"""Derive runtime UI translations from the pinned complete canonical catalog.

The key inventory comes from implemented page/control contracts, never from a
second manually maintained translation list. Generated output is portable C89.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import struct
import zlib

from generate_i18n_catalog import MAGIC, placeholders

ROOT = Path(__file__).resolve().parents[1]


def load_catalog(root=ROOT):
    lock = json.loads((root / "config/i18n-lock.json").read_text())
    raw = (root / lock["catalog_path"]).read_bytes()
    if (len(raw) != lock["catalog_bytes"] or
            len(raw) > lock["maximum_catalog_bytes"] or
            hashlib.sha256(raw).hexdigest() != lock["catalog_sha256"]):
        raise ValueError("canonical catalog differs from pinned lock")
    if not raw.startswith(MAGIC):
        raise ValueError("invalid canonical catalog marker")
    size, count = struct.unpack(">II", raw[len(MAGIC):len(MAGIC) + 8])
    if size > 64 * 1024 * 1024:
        raise ValueError("canonical catalog is too large")
    payload = zlib.decompress(raw[len(MAGIC) + 8:])
    if len(payload) != size:
        raise ValueError("canonical payload length mismatch")
    data = json.loads(payload)
    languages = data["languages"]
    if (data["source_revision"] != lock["source_revision"] or
            count != lock["language_count"] or len(languages) != count):
        raise ValueError("canonical revision/language count mismatch")
    tags = [language["tag"] for language in languages]
    if len(set(tags)) != len(tags) or "en" not in tags:
        raise ValueError("duplicate language tag or missing English")
    english = next(language["entries"] for language in languages if language["tag"] == "en")
    keys = [key for key, _ in english]
    if len(set(keys)) != len(keys) or len(keys) != lock["english_key_count"]:
        raise ValueError("invalid English inventory")
    for language in languages:
        if [key for key, _ in language["entries"]] != keys:
            raise ValueError("canonical language key/order mismatch")
    return lock, languages


def ui_keys(source):
    controls = re.findall(r'\{WENA_UI_[A-Z_]+,\s*"([^"\n]+)"', source)
    pages = re.findall(r'\{"/[^"\n]*",\s*"([^"\n]+)"\}', source)
    if not controls or not pages:
        raise ValueError("missing control/page translation inventory")
    return sorted(set(controls + pages))


def selected_catalog(root=ROOT):
    lock, languages = load_catalog(root)
    keys = ui_keys((root / "imports/ui/page_contract.c").read_text())
    english = dict(next(language["entries"] for language in languages if language["tag"] == "en"))
    for key in keys:
        if key not in english:
            raise ValueError("UI key is not canonical: " + key)
        if placeholders(english[key]):
            raise ValueError("UI key needs an explicit formatter: " + key)
    selected = []
    for language in languages:
        entries = dict(language["entries"])
        row = []
        for key in keys:
            value = entries[key]
            if not isinstance(value, str) or "\0" in value:
                raise ValueError("invalid canonical UI value")
            if placeholders(value) != placeholders(english[key]):
                raise ValueError("canonical UI placeholder mismatch")
            # A short single C literal remains within C89's 509-character
            # minimum after decoding, even for non-ASCII UTF-8 translations.
            if len(value.encode("utf-8")) > 500:
                raise ValueError("UI value exceeds C89 literal bound")
            row.append(value)
        selected.append((language["tag"], row))
    return lock, keys, selected


def literal(value):
    # Fixed-width octal prevents a following digit from extending an escape;
    # escaping question marks also avoids C89 trigraph interpretation.
    return '"' + ''.join(chr(byte) if 32 <= byte <= 126 and byte not in (34, 63, 92)
                         else '\\%03o' % byte for byte in value.encode("utf-8")) + '"'


def generate(root=ROOT):
    lock, keys, languages = selected_catalog(root)
    lines = ["/* Generated by scripts/generate_ui_i18n.py; do not edit.",
             " * Source: canonical WeKan MIT translations, Lauri Ojansivu and contributors.",
             " * Revision: " + lock["source_revision"],
             " * Catalog SHA-256: " + lock["catalog_sha256"], " */",
             "#define WENA_UI_CATALOG_KEY_COUNT %du" % len(keys),
             "#define WENA_UI_CATALOG_LANGUAGE_COUNT %du" % len(languages),
             "static const char *const ui_keys[] = {"]
    lines.extend("    " + literal(key) + "," for key in keys)
    lines.extend(["};", "static const char *const ui_languages[] = {"])
    lines.extend("    " + literal(tag) + "," for tag, _ in languages)
    lines.extend(["};", "static const char *const ui_values[WENA_UI_CATALOG_LANGUAGE_COUNT][WENA_UI_CATALOG_KEY_COUNT] = {"])
    for tag, values in languages:
        lines.append("    { /* " + tag + " */")
        lines.extend("        " + literal(value) + "," for value in values)
        lines.append("    },")
    lines.extend(["};", ""])
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path, default=ROOT / "imports/i18n/ui_catalog_data.h")
    args = parser.parse_args()
    try:
        output = generate()
    except (ValueError, KeyError, zlib.error) as error:
        raise SystemExit(str(error)) from error
    if args.check:
        if not args.output.is_file() or args.output.read_text() != output:
            raise SystemExit("stale generated UI catalog: " + str(args.output))
        print("verified canonical runtime UI translations")
    else:
        args.output.write_text(output, encoding="ascii")
        print("wrote " + str(args.output))


if __name__ == "__main__":
    main()
