#!/usr/bin/env python3
"""WeKan's board defaults, compiled in.

    generate_wekan_defaults.py           -> writes server/wekan_defaults_data.h
    generate_wekan_defaults.py --check   -> fails when that file is stale

A board WeKan makes carries its schema's defaults (models/boards.js:
allowsDescriptionText, allowsChecklists ... and 99 more); WeKan reads a field
that is not there as false and hides that part of the board. A board Wena
makes carries the same, read from WeKan's own schema when its checkout is
here (WEKAN_ROOT, default the checkout Wena is in), and from this header
otherwise - so the check passes without WeKan.
"""
import json
import os
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / "server" / "wekan_defaults_data.h"


def wekan_root():
    return Path(os.environ.get("WEKAN_ROOT") or ROOT.parents[1])


def board_defaults(models):
    """Every Boolean field of WeKan's boards schema with its default, in order."""
    source = (models / "boards.js").read_text(encoding="utf-8")
    found = {}
    for match in re.finditer(r"\n    (\w+): \{(.*?)\n    \},", source, re.S):
        kind = re.search(r"type:\s*(\w+)", match.group(2))
        default = re.search(r"defaultValue:\s*(true|false)\b", match.group(2))
        if kind and default and kind.group(1) == "Boolean":
            found[match.group(1)] = default.group(1) == "true"
    for match in re.finditer(r"\n    (\w+): \{ type: Boolean, defaultValue: (true|false) \}", source):
        found[match.group(1)] = match.group(2) == "true"
    return found


def header(defaults):
    lines = ["/* Generated by scripts/generate_wekan_defaults.py from WeKan's models/boards.js; do not edit. */",
             "/* The Boolean fields a board WeKan makes carries, with their defaults. */",
             "static const char *const wekan_board_boolean_defaults[] = {"]
    items = [f'"\\"{name}\\":{"true" if value else "false"}"' for name, value in defaults.items()]
    for item in items:
        lines.append(f"    {item},")
    lines += ["    0", "};", ""]
    return "\n".join(lines)


def current():
    """The defaults in the committed header."""
    if not HEADER.is_file():
        return {}
    return {m.group(1): m.group(2) == "true"
            for m in re.finditer(r'"\\"(\w+)\\":(true|false)"', HEADER.read_text(encoding="utf-8"))}


def main(argv):
    models = wekan_root() / "models"
    have_wekan = (models / "boards.js").is_file()
    if "--check" in argv:
        if not have_wekan:
            print("WeKan's models not here: kept server/wekan_defaults_data.h as it is")
            return 0
        if current() != board_defaults(models):
            print("server/wekan_defaults_data.h is stale: run scripts/generate_wekan_defaults.py", file=sys.stderr)
            return 1
        print("verified WeKan's board defaults")
        return 0
    if not have_wekan:
        print(f"WeKan's models are not at {models}; set WEKAN_ROOT", file=sys.stderr)
        return 1
    HEADER.write_text(header(board_defaults(models)), encoding="utf-8")
    print(f"wrote {HEADER} ({len(board_defaults(models))} fields)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
