#!/usr/bin/env python3
"""WeKan's header logo, compiled in.

    generate_wekan_logo.py           -> writes client/platform/logo_data.h
    generate_wekan_logo.py --check   -> fails when that file is stale

WeKan's header shows public/logo-header.png beside the board's title
(client/components/main/header.jade, .header-logo). Wena draws the same
image, decoded by models/image_decode.c, from these bytes: taken from
WeKan's checkout when it is here (WEKAN_ROOT, default the checkout Wena is
in), else the header is checked against its own recorded SHA-256 - so the
check passes without WeKan.
"""
import hashlib
import os
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / "client" / "platform" / "logo_data.h"


def source():
    path = Path(os.environ.get("WEKAN_ROOT") or (ROOT.parents[1] if len(ROOT.parents) > 1 else ROOT)) / "public" / "logo-header.png"
    return path.read_bytes() if path.is_file() else None


def render(data):
    lines = ["/* Generated by scripts/generate_wekan_logo.py from WeKan's public/logo-header.png;",
             " * do not edit. WeKan, MIT, Lauri Ojansivu and contributors.",
             " * SHA-256: " + hashlib.sha256(data).hexdigest() + " */",
             "#define WENA_LOGO_BYTES %du" % len(data),
             "static const unsigned char wena_logo_png[WENA_LOGO_BYTES] = {"]
    for offset in range(0, len(data), 16):
        lines.append("    " + ",".join("0x%02x" % b for b in data[offset:offset + 16]) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    data = source()
    if "--check" in sys.argv:
        if not HEADER.is_file():
            sys.exit("missing %s: run scripts/generate_wekan_logo.py" % HEADER)
        text = HEADER.read_text()
        if data is None:
            # Without WeKan: the header's bytes must still be what it records.
            body = bytes(int(v, 16) for v in re.findall(r"0x([0-9a-f]{2})", text.split("= {", 1)[1]))
            recorded = re.search(r"SHA-256: ([0-9a-f]{64})", text).group(1)
            if hashlib.sha256(body).hexdigest() != recorded:
                sys.exit("%s is damaged: its bytes do not match its SHA-256" % HEADER)
        elif text != render(data):
            sys.exit("%s is stale: run scripts/generate_wekan_logo.py" % HEADER)
        print("WeKan header logo verified")
        return
    if data is None:
        sys.exit("WeKan's public/logo-header.png is not here (set WEKAN_ROOT)")
    HEADER.write_text(render(data))
    print("wrote %s" % HEADER)


if __name__ == "__main__":
    main()
