#!/usr/bin/env python3
"""Compile the licenses of everything in a Wena executable into it.

    generate_notices.py           -> writes client/platform/notices_data.h
    generate_notices.py --check   -> fails when that file is stale

A release is one executable per platform and nothing beside it, so the
licenses and provenance that must travel with SDL2, SQLite, Nuklear, the
Roboto font and WeKan's translations are inside it: `wena --licenses`
prints them. The text is emitted as a byte array, which every C89 compiler
accepts whatever its string-literal length limit.
"""

from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / "client" / "platform" / "notices_data.h"
# (title, source) in the order they are printed.
NOTICES = (
    ("Wena (MIT)", "LICENSE"),
    ("Nuklear (MIT or public domain)", "third_party/nuklear/LICENSE"),
    ("SDL2 (Zlib), linked in", "third_party/licenses/SDL2-LICENSE.txt"),
    ("SQLite (public domain), linked in", "third_party/licenses/SQLITE.txt"),
    ("Roboto font (Apache-2.0), embedded", "third_party/fonts/LICENSE-Roboto.txt"),
    ("Roboto font provenance", "third_party/fonts/provenance.json"),
    ("Translations from WeKan (MIT)", "imports/i18n/README.md"),
    ("Pinned sources of what is linked in", "config/release-dependencies.json"),
)


def text(root=ROOT):
    parts = []
    for title, source in NOTICES:
        body = (Path(root) / source).read_text(encoding="utf-8").rstrip("\n")
        parts.append(f"==== {title} ({source}) ====\n\n{body}\n")
    return "\n".join(parts)


def header(root=ROOT):
    data = text(root).encode("utf-8")
    lines = ["/* Generated by scripts/generate_notices.py; do not edit. */",
             "static const unsigned char wena_notices[] = {"]
    for offset in range(0, len(data), 16):
        lines.append("    " + ",".join(str(byte) for byte in data[offset:offset + 16]) + ",")
    lines += ["    0", "};", ""]
    return "\n".join(lines)


def main(argv):
    expected = header()
    if argv == ["--check"]:
        if not HEADER.is_file() or HEADER.read_text(encoding="utf-8") != expected:
            print("client/platform/notices_data.h is stale: run scripts/generate_notices.py",
                  file=sys.stderr)
            return 1
        print("verified compiled license notices")
        return 0
    if argv:
        print("Usage: generate_notices.py [--check]", file=sys.stderr)
        return 2
    HEADER.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
