#!/usr/bin/env python3
"""Verify immutable, ordered migrations and their compiled C89 registry."""
import argparse
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
V1_SHA256 = "e4760a2b70d6651ee84dce93642ccdd4ce8991b488dece5d231e66053f065da5"
V2_SHA256 = "429503c784a355f492d4ca6e65428a5e38375ec9d04fc63d264a9ffe1cf6ad83"
V3_SHA256 = "944b67e3548c07694a86f630fa3acd0d61bd298e8df5c648d9bb2d7da6fc886c"
V4_SHA256 = "0d3dd3c932a4c710fdba04b3d7eda22efaa2693a411369d2cdc6368b8898606c"
V5_SHA256 = "ed5db1279fac66f43648bd6a309335cf272e7b4b868b6ea950252ab1e5304317"
V6_SHA256 = "d4d89950ca938a52ff238ef57b44ee6bc54996c7361a45a1d519183acb3c50ed"
V7_SHA256 = "e67771f1a9b59a15e3681a003db247919c26b9fef4c92a4ecf8dae5a8dd29a86"
V8_SHA256 = "20d32a701cd08e370fd45afda40b1bf3db278feda0266f91546071b175d58cd4"
V9_SHA256 = "e69c2dd37a03beb1c404223e212abe920fa88b9f5aad9fa561ae01ac4a4b6e7d"
V10_SHA256 = "569f851244e439b5106cf081ad43a07fb026eed894bef133368ba7cda48bcc1d"
V11_SHA256 = "9c5a04b32f44bd3327ea08ee4ac21b6ba14c7d28aba3a77ebbf6e09f99146070"
PATHS = ("server/migrations/001_initial.sql", "server/migrations/002_card_descriptions.sql",
         "server/migrations/003_checklists.sql", "server/migrations/004_checklist_item_card_order.sql",
         "server/migrations/005_labels.sql", "server/migrations/006_board_settings.sql",
         "server/migrations/007_board_minicard_settings.sql",
         "server/migrations/008_actor_card_sections.sql",
         "server/migrations/009_board_card_collapse.sql",
         "server/migrations/010_list_archive_state.sql",
         "server/migrations/011_hierarchy_colors.sql",
         "server/migrations/012_list_wip_limits.sql")
HEADER = "server/migrations/compiled_registry.h"


def registry(root):
    programs = [(root / path).read_bytes() for path in PATHS]
    if hashlib.sha256(programs[0]).hexdigest() != V1_SHA256:
        raise SystemExit("published v1 migration is immutable")
    if hashlib.sha256(programs[1]).hexdigest() != V2_SHA256:
        raise SystemExit("published v2 migration is immutable")
    if hashlib.sha256(programs[2]).hexdigest() != V3_SHA256:
        raise SystemExit("published v3 migration is immutable")
    if hashlib.sha256(programs[3]).hexdigest() != V4_SHA256:
        raise SystemExit("published v4 migration is immutable")
    if hashlib.sha256(programs[4]).hexdigest() != V5_SHA256:
        raise SystemExit("published v5 migration is immutable")
    if hashlib.sha256(programs[5]).hexdigest() != V6_SHA256:
        raise SystemExit("published v6 migration is immutable")
    if hashlib.sha256(programs[6]).hexdigest() != V7_SHA256:
        raise SystemExit("published v7 migration is immutable")
    if hashlib.sha256(programs[7]).hexdigest() != V8_SHA256:
        raise SystemExit("published v8 migration is immutable")
    if hashlib.sha256(programs[8]).hexdigest() != V9_SHA256:
        raise SystemExit("published v9 migration is immutable")
    if hashlib.sha256(programs[9]).hexdigest() != V10_SHA256:
        raise SystemExit("published v10 migration is immutable")
    if hashlib.sha256(programs[10]).hexdigest() != V11_SHA256:
        raise SystemExit("published v11 migration is immutable")
    entries = []
    bundle = b""
    for version, (path, program) in enumerate(zip(PATHS, programs), 1):
        if b"BEGIN" in program or b"COMMIT" in program or b"user_version" in program:
            raise SystemExit("migration transaction/version must be owned by the runner")
        program.decode("ascii")
        bundle += program
        entries.append({"version": version, "path": path, "sha256": hashlib.sha256(program).hexdigest(),
                        "size": len(program), "bundle_sha256": hashlib.sha256(bundle).hexdigest(),
                        "bundle_size": len(bundle)})
    return {"format": 2, "schema_version": len(entries), "migrations": entries}, programs, bundle


def compiled_header(lock, programs):
    lines = ["/* Generated by scripts/verify_migrations.py --generate; review SQL and lock. */",
             "#if defined(__GNUC__)", "#pragma GCC diagnostic push",
             '#pragma GCC diagnostic ignored "-Woverlength-strings"', "#endif"]
    for entry, program in zip(lock["migrations"], programs):
        lines.append("static const char migration_v%d[] =" % entry["version"])
        lines.extend(json.dumps(line.decode("ascii")) for line in program.splitlines(keepends=True))
        lines[-1] += ";"
    lines.extend(["static const WenaCompiledMigration migrations[] = {"])
    for entry in lock["migrations"]:
        lines.append('    {%d, migration_v%d, %du, "%s", %du, "%s"},' %
                     (entry["version"], entry["version"], entry["size"], entry["sha256"],
                      entry["bundle_size"], entry["bundle_sha256"]))
    lines.extend(["};", "static const WenaSchemaObject schema_objects[] = {"])
    # The new additive DDL consists only of CREATE TABLE/INDEX statements.
    # Preserve its exact SQL to detect altered constraints as well as names.
    for entry, program in zip(lock["migrations"][1:], programs[1:]):
        for statement in program.decode("ascii").split(";"):
            statement = statement.strip()
            if not statement:
                continue
            match = re.match(r"CREATE (?:UNIQUE )?(TABLE|INDEX) ([a-z][a-z0-9_]*)[ (]", statement)
            if not match:
                raise SystemExit("unsupported schema-object DDL; extend and review the registry generator")
            lines.append('    {%d, "%s", "%s", %s},' %
                         (entry["version"], match[2], match[1].lower(), json.dumps(statement)))
    lines.extend(["};", "#if defined(__GNUC__)", "#pragma GCC diagnostic pop", "#endif", ""])
    return "\n".join(lines)


def verify(root=ROOT):
    expected, programs, bundle = registry(root)
    lock = json.loads((root / "config/migrations-lock.json").read_text(encoding="utf-8"))
    if lock != expected:
        raise SystemExit("SQLite migration lock is stale; regenerate and review it")
    if (root / HEADER).read_text(encoding="ascii") != compiled_header(expected, programs):
        raise SystemExit("compiled migration registry is stale; regenerate and review it")
    return lock, bundle


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--generate", action="store_true", help="rewrite reviewed lock and compiled header")
    parser.add_argument("--check", action="store_true", help="verify only (default)")
    args = parser.parse_args()
    if args.generate and args.check:
        parser.error("choose generate or check")
    if args.generate:
        lock, programs, _ = registry(ROOT)
        (ROOT / "config/migrations-lock.json").write_text(json.dumps(lock, indent=2) + "\n", encoding="utf-8")
        (ROOT / HEADER).write_text(compiled_header(lock, programs), encoding="ascii")
    verify()
