#!/usr/bin/env python3
"""Verify immutable, ordered migrations and their compiled C89 registry."""
import argparse
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
V1_SHA256 = "e4760a2b70d6651ee84dce93642ccdd4ce8991b488dece5d231e66053f065da5"
V2_SHA256 = "429503c784a355f492d4ca6e65428a5e38375ec9d04fc63d264a9ffe1cf6ad83"
V3_SHA256 = "944b67e3548c07694a86f630fa3acd0d61bd298e8df5c648d9bb2d7da6fc886c"
PATHS = ("server/migrations/001_initial.sql", "server/migrations/002_card_descriptions.sql",
         "server/migrations/003_checklists.sql", "server/migrations/004_checklist_item_card_order.sql")
HEADER = "server/migrations/compiled_registry.h"


def registry(root):
    programs = [(root / path).read_bytes() for path in PATHS]
    if hashlib.sha256(programs[0]).hexdigest() != V1_SHA256:
        raise SystemExit("published v1 migration is immutable")
    if hashlib.sha256(programs[1]).hexdigest() != V2_SHA256:
        raise SystemExit("published v2 migration is immutable")
    if hashlib.sha256(programs[2]).hexdigest() != V3_SHA256:
        raise SystemExit("published v3 migration is immutable")
    entries = []
    bundle = b""
    for version, (path, program) in enumerate(zip(PATHS, programs), 1):
        if b"BEGIN" in program or b"COMMIT" in program or b"user_version" in program:
            raise SystemExit("migration transaction/version must be owned by the runner")
        program.decode("ascii")
        bundle += program
        entries.append({"version": version, "path": path, "sha256": hashlib.sha256(program).hexdigest(),
                        "size": len(program), "bundle_sha256": hashlib.sha256(bundle).hexdigest(),
                        "bundle_size": len(bundle)})
    return {"format": 2, "schema_version": len(entries), "migrations": entries}, programs, bundle


def compiled_header(lock, programs):
    lines = ["/* Generated by scripts/verify_migrations.py --generate; review SQL and lock. */",
             "#if defined(__GNUC__)", "#pragma GCC diagnostic push",
             '#pragma GCC diagnostic ignored "-Woverlength-strings"', "#endif"]
    for entry, program in zip(lock["migrations"], programs):
        lines.append("static const char migration_v%d[] =" % entry["version"])
        lines.extend(json.dumps(line.decode("ascii")) for line in program.splitlines(keepends=True))
        lines[-1] += ";"
    lines.extend(["static const WenaCompiledMigration migrations[] = {"])
    for entry in lock["migrations"]:
        lines.append('    {%d, migration_v%d, %du, "%s", %du, "%s"},' %
                     (entry["version"], entry["version"], entry["size"], entry["sha256"],
                      entry["bundle_size"], entry["bundle_sha256"]))
    lines.extend(["};", "static const WenaSchemaObject schema_objects[] = {"])
    # The new additive DDL consists only of CREATE TABLE/INDEX statements.
    # Preserve its exact SQL to detect altered constraints as well as names.
    for entry, program in zip(lock["migrations"][1:], programs[1:]):
        for statement in program.decode("ascii").split(";"):
            statement = statement.strip()
            if not statement:
                continue
            match = re.match(r"CREATE (?:UNIQUE )?(TABLE|INDEX) ([a-z][a-z0-9_]*)[ (]", statement)
            if not match:
                raise SystemExit("unsupported schema-object DDL; extend and review the registry generator")
            lines.append('    {%d, "%s", "%s", %s},' %
                         (entry["version"], match[2], match[1].lower(), json.dumps(statement)))
    lines.extend(["};", "#if defined(__GNUC__)", "#pragma GCC diagnostic pop", "#endif", ""])
    return "\n".join(lines)


def verify(root=ROOT):
    expected, programs, bundle = registry(root)
    lock = json.loads((root / "config/migrations-lock.json").read_text(encoding="utf-8"))
    if lock != expected:
        raise SystemExit("SQLite migration lock is stale; regenerate and review it")
    if (root / HEADER).read_text(encoding="ascii") != compiled_header(expected, programs):
        raise SystemExit("compiled migration registry is stale; regenerate and review it")
    return lock, bundle


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--generate", action="store_true", help="rewrite reviewed lock and compiled header")
    parser.add_argument("--check", action="store_true", help="verify only (default)")
    args = parser.parse_args()
    if args.generate and args.check:
        parser.error("choose generate or check")
    if args.generate:
        lock, programs, _ = registry(ROOT)
        (ROOT / "config/migrations-lock.json").write_text(json.dumps(lock, indent=2) + "\n", encoding="utf-8")
        (ROOT / HEADER).write_text(compiled_header(lock, programs), encoding="ascii")
    verify()
