/* Generated by scripts/verify_migrations.py --generate; review SQL and lock. */
#if defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Woverlength-strings"
#endif
static const char migration_v1[] =
"CREATE TABLE schema_migrations (\n"
"  version INTEGER PRIMARY KEY,\n"
"  checksum TEXT NOT NULL UNIQUE,\n"
"  applied_at INTEGER NOT NULL\n"
");\n"
"CREATE TABLE actors (\n"
"  id TEXT PRIMARY KEY,\n"
"  display_name TEXT NOT NULL,\n"
"  version INTEGER NOT NULL CHECK (version > 0)\n"
");\n"
"CREATE TABLE sessions (\n"
"  id TEXT PRIMARY KEY,\n"
"  actor_id TEXT NOT NULL REFERENCES actors(id) ON DELETE RESTRICT,\n"
"  expires_at INTEGER NOT NULL,\n"
"  revoked INTEGER NOT NULL DEFAULT 0 CHECK (revoked IN (0, 1))\n"
");\n"
"CREATE INDEX sessions_actor_idx ON sessions(actor_id);\n"
"CREATE TABLE boards (\n"
"  id TEXT PRIMARY KEY,\n"
"  title TEXT NOT NULL,\n"
"  version INTEGER NOT NULL CHECK (version > 0)\n"
");\n"
"CREATE TABLE swimlanes (\n"
"  id TEXT PRIMARY KEY,\n"
"  board_id TEXT NOT NULL REFERENCES boards(id) ON DELETE RESTRICT,\n"
"  title TEXT NOT NULL,\n"
"  position INTEGER NOT NULL CHECK (position >= 0),\n"
"  version INTEGER NOT NULL CHECK (version > 0),\n"
"  UNIQUE (board_id, id),\n"
"  UNIQUE (board_id, position)\n"
");\n"
"CREATE TABLE lists (\n"
"  id TEXT PRIMARY KEY,\n"
"  board_id TEXT NOT NULL REFERENCES boards(id) ON DELETE RESTRICT,\n"
"  title TEXT NOT NULL,\n"
"  position INTEGER NOT NULL CHECK (position >= 0),\n"
"  version INTEGER NOT NULL CHECK (version > 0),\n"
"  UNIQUE (board_id, id),\n"
"  UNIQUE (board_id, position)\n"
");\n"
"CREATE TABLE cards (\n"
"  id TEXT PRIMARY KEY,\n"
"  board_id TEXT NOT NULL REFERENCES boards(id) ON DELETE RESTRICT,\n"
"  swimlane_id TEXT NOT NULL,\n"
"  list_id TEXT NOT NULL,\n"
"  title TEXT NOT NULL,\n"
"  position INTEGER NOT NULL CHECK (position >= 0),\n"
"  archived INTEGER NOT NULL DEFAULT 0 CHECK (archived IN (0, 1)),\n"
"  version INTEGER NOT NULL CHECK (version > 0),\n"
"  UNIQUE (list_id, swimlane_id, position),\n"
"  FOREIGN KEY (board_id, swimlane_id) REFERENCES swimlanes(board_id, id) ON DELETE RESTRICT,\n"
"  FOREIGN KEY (board_id, list_id) REFERENCES lists(board_id, id) ON DELETE RESTRICT\n"
");\n"
"CREATE INDEX cards_board_idx ON cards(board_id);\n"
"CREATE INDEX cards_swimlane_idx ON cards(swimlane_id);\n"
"CREATE TABLE idempotency_keys (\n"
"  actor_id TEXT NOT NULL REFERENCES actors(id) ON DELETE RESTRICT,\n"
"  route TEXT NOT NULL,\n"
"  operation TEXT NOT NULL,\n"
"  request_version INTEGER NOT NULL CHECK (request_version > 0),\n"
"  response_checksum TEXT NOT NULL,\n"
"  committed_at INTEGER NOT NULL,\n"
"  PRIMARY KEY (actor_id, route, operation, request_version)\n"
");\n";
static const char migration_v2[] =
"CREATE UNIQUE INDEX cards_board_id_unique ON cards(board_id, id);\n"
"CREATE TABLE card_descriptions (\n"
"  card_id TEXT NOT NULL PRIMARY KEY,\n"
"  board_id TEXT NOT NULL,\n"
"  description TEXT NOT NULL DEFAULT '' CHECK (\n"
"    typeof(description) = 'text' AND\n"
"    length(CAST(description AS BLOB)) <= 1024 AND\n"
"    instr(description, char(0)) = 0\n"
"  ),\n"
"  FOREIGN KEY (board_id, card_id) REFERENCES cards(board_id, id) ON DELETE RESTRICT\n"
");\n";
static const char migration_v3[] =
"CREATE TABLE checklists (\n"
"  id TEXT NOT NULL PRIMARY KEY CHECK (typeof(id) = 'text' AND length(CAST(id AS BLOB)) BETWEEN 1 AND 64 AND instr(id, char(0)) = 0),\n"
"  board_id TEXT NOT NULL,\n"
"  card_id TEXT NOT NULL,\n"
"  title TEXT NOT NULL CHECK (typeof(title) = 'text' AND length(CAST(title AS BLOB)) BETWEEN 1 AND 128 AND instr(title, char(0)) = 0),\n"
"  position INTEGER NOT NULL CHECK (typeof(position) = 'integer' AND position BETWEEN 0 AND 2147483647),\n"
"  hide_checked_items INTEGER NOT NULL DEFAULT 0 CHECK (typeof(hide_checked_items) = 'integer' AND hide_checked_items IN (0, 1)),\n"
"  hide_all_items INTEGER NOT NULL DEFAULT 0 CHECK (typeof(hide_all_items) = 'integer' AND hide_all_items IN (0, 1)),\n"
"  show_on_minicard INTEGER DEFAULT NULL CHECK (show_on_minicard IS NULL OR (typeof(show_on_minicard) = 'integer' AND show_on_minicard IN (0, 1))),\n"
"  version INTEGER NOT NULL DEFAULT 1 CHECK (typeof(version) = 'integer' AND version > 0),\n"
"  created_at INTEGER NOT NULL DEFAULT 0 CHECK (typeof(created_at) = 'integer' AND created_at >= 0),\n"
"  updated_at INTEGER NOT NULL DEFAULT 0 CHECK (typeof(updated_at) = 'integer' AND updated_at >= 0),\n"
"  UNIQUE (board_id, card_id, id),\n"
"  UNIQUE (card_id, position),\n"
"  FOREIGN KEY (board_id, card_id) REFERENCES cards(board_id, id) ON DELETE RESTRICT\n"
");\n"
"CREATE TABLE checklist_items (\n"
"  id TEXT NOT NULL PRIMARY KEY CHECK (typeof(id) = 'text' AND length(CAST(id AS BLOB)) BETWEEN 1 AND 64 AND instr(id, char(0)) = 0),\n"
"  board_id TEXT NOT NULL,\n"
"  card_id TEXT NOT NULL,\n"
"  checklist_id TEXT NOT NULL,\n"
"  title TEXT NOT NULL CHECK (typeof(title) = 'text' AND length(CAST(title AS BLOB)) BETWEEN 1 AND 128 AND instr(title, char(0)) = 0),\n"
"  position INTEGER NOT NULL CHECK (typeof(position) = 'integer' AND position BETWEEN 0 AND 2147483647),\n"
"  is_finished INTEGER NOT NULL DEFAULT 0 CHECK (typeof(is_finished) = 'integer' AND is_finished IN (0, 1)),\n"
"  version INTEGER NOT NULL DEFAULT 1 CHECK (typeof(version) = 'integer' AND version > 0),\n"
"  created_at INTEGER NOT NULL DEFAULT 0 CHECK (typeof(created_at) = 'integer' AND created_at >= 0),\n"
"  updated_at INTEGER NOT NULL DEFAULT 0 CHECK (typeof(updated_at) = 'integer' AND updated_at >= 0),\n"
"  UNIQUE (checklist_id, position),\n"
"  FOREIGN KEY (board_id, card_id, checklist_id) REFERENCES checklists(board_id, card_id, id) ON DELETE RESTRICT\n"
");\n";
static const char migration_v4[] =
"CREATE INDEX checklist_items_card_order_idx ON checklist_items(card_id, checklist_id, position, id);\n";
static const WenaCompiledMigration migrations[] = {
    {1, migration_v1, 2249u, "e4760a2b70d6651ee84dce93642ccdd4ce8991b488dece5d231e66053f065da5", 2249u, "e4760a2b70d6651ee84dce93642ccdd4ce8991b488dece5d231e66053f065da5"},
    {2, migration_v2, 424u, "429503c784a355f492d4ca6e65428a5e38375ec9d04fc63d264a9ffe1cf6ad83", 2673u, "0653cc5cce0527d8ed5b4f10e184f82b0636d4aee83a5ca27914db7f8f8d7919"},
    {3, migration_v3, 2313u, "944b67e3548c07694a86f630fa3acd0d61bd298e8df5c648d9bb2d7da6fc886c", 4986u, "80a19517e0633f8f1445e136c6560c2e2f88b6349b0d2d99f1146433f9a9d704"},
    {4, migration_v4, 101u, "0d3dd3c932a4c710fdba04b3d7eda22efaa2693a411369d2cdc6368b8898606c", 5087u, "5f315dcf32ce637ebbc147d1cc2522e6ec214fa6a2c32f00b797fec9183c4427"},
};
static const WenaSchemaObject schema_objects[] = {
    {2, "cards_board_id_unique", "index", "CREATE UNIQUE INDEX cards_board_id_unique ON cards(board_id, id)"},
    {2, "card_descriptions", "table", "CREATE TABLE card_descriptions (\n  card_id TEXT NOT NULL PRIMARY KEY,\n  board_id TEXT NOT NULL,\n  description TEXT NOT NULL DEFAULT '' CHECK (\n    typeof(description) = 'text' AND\n    length(CAST(description AS BLOB)) <= 1024 AND\n    instr(description, char(0)) = 0\n  ),\n  FOREIGN KEY (board_id, card_id) REFERENCES cards(board_id, id) ON DELETE RESTRICT\n)"},
    {3, "checklists", "table", "CREATE TABLE checklists (\n  id TEXT NOT NULL PRIMARY KEY CHECK (typeof(id) = 'text' AND length(CAST(id AS BLOB)) BETWEEN 1 AND 64 AND instr(id, char(0)) = 0),\n  board_id TEXT NOT NULL,\n  card_id TEXT NOT NULL,\n  title TEXT NOT NULL CHECK (typeof(title) = 'text' AND length(CAST(title AS BLOB)) BETWEEN 1 AND 128 AND instr(title, char(0)) = 0),\n  position INTEGER NOT NULL CHECK (typeof(position) = 'integer' AND position BETWEEN 0 AND 2147483647),\n  hide_checked_items INTEGER NOT NULL DEFAULT 0 CHECK (typeof(hide_checked_items) = 'integer' AND hide_checked_items IN (0, 1)),\n  hide_all_items INTEGER NOT NULL DEFAULT 0 CHECK (typeof(hide_all_items) = 'integer' AND hide_all_items IN (0, 1)),\n  show_on_minicard INTEGER DEFAULT NULL CHECK (show_on_minicard IS NULL OR (typeof(show_on_minicard) = 'integer' AND show_on_minicard IN (0, 1))),\n  version INTEGER NOT NULL DEFAULT 1 CHECK (typeof(version) = 'integer' AND version > 0),\n  created_at INTEGER NOT NULL DEFAULT 0 CHECK (typeof(created_at) = 'integer' AND created_at >= 0),\n  updated_at INTEGER NOT NULL DEFAULT 0 CHECK (typeof(updated_at) = 'integer' AND updated_at >= 0),\n  UNIQUE (board_id, card_id, id),\n  UNIQUE (card_id, position),\n  FOREIGN KEY (board_id, card_id) REFERENCES cards(board_id, id) ON DELETE RESTRICT\n)"},
    {3, "checklist_items", "table", "CREATE TABLE checklist_items (\n  id TEXT NOT NULL PRIMARY KEY CHECK (typeof(id) = 'text' AND length(CAST(id AS BLOB)) BETWEEN 1 AND 64 AND instr(id, char(0)) = 0),\n  board_id TEXT NOT NULL,\n  card_id TEXT NOT NULL,\n  checklist_id TEXT NOT NULL,\n  title TEXT NOT NULL CHECK (typeof(title) = 'text' AND length(CAST(title AS BLOB)) BETWEEN 1 AND 128 AND instr(title, char(0)) = 0),\n  position INTEGER NOT NULL CHECK (typeof(position) = 'integer' AND position BETWEEN 0 AND 2147483647),\n  is_finished INTEGER NOT NULL DEFAULT 0 CHECK (typeof(is_finished) = 'integer' AND is_finished IN (0, 1)),\n  version INTEGER NOT NULL DEFAULT 1 CHECK (typeof(version) = 'integer' AND version > 0),\n  created_at INTEGER NOT NULL DEFAULT 0 CHECK (typeof(created_at) = 'integer' AND created_at >= 0),\n  updated_at INTEGER NOT NULL DEFAULT 0 CHECK (typeof(updated_at) = 'integer' AND updated_at >= 0),\n  UNIQUE (checklist_id, position),\n  FOREIGN KEY (board_id, card_id, checklist_id) REFERENCES checklists(board_id, card_id, id) ON DELETE RESTRICT\n)"},
    {4, "checklist_items_card_order_idx", "index", "CREATE INDEX checklist_items_card_order_idx ON checklist_items(card_id, checklist_id, position, id)"},
};
#if defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
