/* Generated by scripts/verify_migrations.py --generate; review SQL and lock. */
#if defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Woverlength-strings"
#endif
static const char migration_v1[] =
"CREATE TABLE schema_migrations (\n"
"  version INTEGER PRIMARY KEY,\n"
"  checksum TEXT NOT NULL UNIQUE,\n"
"  applied_at INTEGER NOT NULL\n"
");\n"
"CREATE TABLE actors (\n"
"  id TEXT PRIMARY KEY,\n"
"  display_name TEXT NOT NULL,\n"
"  version INTEGER NOT NULL CHECK (version > 0)\n"
");\n"
"CREATE TABLE sessions (\n"
"  id TEXT PRIMARY KEY,\n"
"  actor_id TEXT NOT NULL REFERENCES actors(id) ON DELETE RESTRICT,\n"
"  expires_at INTEGER NOT NULL,\n"
"  revoked INTEGER NOT NULL DEFAULT 0 CHECK (revoked IN (0, 1))\n"
");\n"
"CREATE INDEX sessions_actor_idx ON sessions(actor_id);\n"
"CREATE TABLE boards (\n"
"  id TEXT PRIMARY KEY,\n"
"  title TEXT NOT NULL,\n"
"  version INTEGER NOT NULL CHECK (version > 0)\n"
");\n"
"CREATE TABLE swimlanes (\n"
"  id TEXT PRIMARY KEY,\n"
"  board_id TEXT NOT NULL REFERENCES boards(id) ON DELETE RESTRICT,\n"
"  title TEXT NOT NULL,\n"
"  position INTEGER NOT NULL CHECK (position >= 0),\n"
"  version INTEGER NOT NULL CHECK (version > 0),\n"
"  UNIQUE (board_id, id),\n"
"  UNIQUE (board_id, position)\n"
");\n"
"CREATE TABLE lists (\n"
"  id TEXT PRIMARY KEY,\n"
"  board_id TEXT NOT NULL REFERENCES boards(id) ON DELETE RESTRICT,\n"
"  title TEXT NOT NULL,\n"
"  position INTEGER NOT NULL CHECK (position >= 0),\n"
"  version INTEGER NOT NULL CHECK (version > 0),\n"
"  UNIQUE (board_id, id),\n"
"  UNIQUE (board_id, position)\n"
");\n"
"CREATE TABLE cards (\n"
"  id TEXT PRIMARY KEY,\n"
"  board_id TEXT NOT NULL REFERENCES boards(id) ON DELETE RESTRICT,\n"
"  swimlane_id TEXT NOT NULL,\n"
"  list_id TEXT NOT NULL,\n"
"  title TEXT NOT NULL,\n"
"  position INTEGER NOT NULL CHECK (position >= 0),\n"
"  archived INTEGER NOT NULL DEFAULT 0 CHECK (archived IN (0, 1)),\n"
"  version INTEGER NOT NULL CHECK (version > 0),\n"
"  UNIQUE (list_id, swimlane_id, position),\n"
"  FOREIGN KEY (board_id, swimlane_id) REFERENCES swimlanes(board_id, id) ON DELETE RESTRICT,\n"
"  FOREIGN KEY (board_id, list_id) REFERENCES lists(board_id, id) ON DELETE RESTRICT\n"
");\n"
"CREATE INDEX cards_board_idx ON cards(board_id);\n"
"CREATE INDEX cards_swimlane_idx ON cards(swimlane_id);\n"
"CREATE TABLE idempotency_keys (\n"
"  actor_id TEXT NOT NULL REFERENCES actors(id) ON DELETE RESTRICT,\n"
"  route TEXT NOT NULL,\n"
"  operation TEXT NOT NULL,\n"
"  request_version INTEGER NOT NULL CHECK (request_version > 0),\n"
"  response_checksum TEXT NOT NULL,\n"
"  committed_at INTEGER NOT NULL,\n"
"  PRIMARY KEY (actor_id, route, operation, request_version)\n"
");\n";
static const char migration_v2[] =
"CREATE UNIQUE INDEX cards_board_id_unique ON cards(board_id, id);\n"
"CREATE TABLE card_descriptions (\n"
"  card_id TEXT NOT NULL PRIMARY KEY,\n"
"  board_id TEXT NOT NULL,\n"
"  description TEXT NOT NULL DEFAULT '' CHECK (\n"
"    typeof(description) = 'text' AND\n"
"    length(CAST(description AS BLOB)) <= 1024 AND\n"
"    instr(description, char(0)) = 0\n"
"  ),\n"
"  FOREIGN KEY (board_id, card_id) REFERENCES cards(board_id, id) ON DELETE RESTRICT\n"
");\n";
static const char migration_v3[] =
"CREATE TABLE checklists (\n"
"  id TEXT NOT NULL PRIMARY KEY CHECK (typeof(id) = 'text' AND length(CAST(id AS BLOB)) BETWEEN 1 AND 64 AND instr(id, char(0)) = 0),\n"
"  board_id TEXT NOT NULL,\n"
"  card_id TEXT NOT NULL,\n"
"  title TEXT NOT NULL CHECK (typeof(title) = 'text' AND length(CAST(title AS BLOB)) BETWEEN 1 AND 128 AND instr(title, char(0)) = 0),\n"
"  position INTEGER NOT NULL CHECK (typeof(position) = 'integer' AND position BETWEEN 0 AND 2147483647),\n"
"  hide_checked_items INTEGER NOT NULL DEFAULT 0 CHECK (typeof(hide_checked_items) = 'integer' AND hide_checked_items IN (0, 1)),\n"
"  hide_all_items INTEGER NOT NULL DEFAULT 0 CHECK (typeof(hide_all_items) = 'integer' AND hide_all_items IN (0, 1)),\n"
"  show_on_minicard INTEGER DEFAULT NULL CHECK (show_on_minicard IS NULL OR (typeof(show_on_minicard) = 'integer' AND show_on_minicard IN (0, 1))),\n"
"  version INTEGER NOT NULL DEFAULT 1 CHECK (typeof(version) = 'integer' AND version > 0),\n"
"  created_at INTEGER NOT NULL DEFAULT 0 CHECK (typeof(created_at) = 'integer' AND created_at >= 0),\n"
"  updated_at INTEGER NOT NULL DEFAULT 0 CHECK (typeof(updated_at) = 'integer' AND updated_at >= 0),\n"
"  UNIQUE (board_id, card_id, id),\n"
"  UNIQUE (card_id, position),\n"
"  FOREIGN KEY (board_id, card_id) REFERENCES cards(board_id, id) ON DELETE RESTRICT\n"
");\n"
"CREATE TABLE checklist_items (\n"
"  id TEXT NOT NULL PRIMARY KEY CHECK (typeof(id) = 'text' AND length(CAST(id AS BLOB)) BETWEEN 1 AND 64 AND instr(id, char(0)) = 0),\n"
"  board_id TEXT NOT NULL,\n"
"  card_id TEXT NOT NULL,\n"
"  checklist_id TEXT NOT NULL,\n"
"  title TEXT NOT NULL CHECK (typeof(title) = 'text' AND length(CAST(title AS BLOB)) BETWEEN 1 AND 128 AND instr(title, char(0)) = 0),\n"
"  position INTEGER NOT NULL CHECK (typeof(position) = 'integer' AND position BETWEEN 0 AND 2147483647),\n"
"  is_finished INTEGER NOT NULL DEFAULT 0 CHECK (typeof(is_finished) = 'integer' AND is_finished IN (0, 1)),\n"
"  version INTEGER NOT NULL DEFAULT 1 CHECK (typeof(version) = 'integer' AND version > 0),\n"
"  created_at INTEGER NOT NULL DEFAULT 0 CHECK (typeof(created_at) = 'integer' AND created_at >= 0),\n"
"  updated_at INTEGER NOT NULL DEFAULT 0 CHECK (typeof(updated_at) = 'integer' AND updated_at >= 0),\n"
"  UNIQUE (checklist_id, position),\n"
"  FOREIGN KEY (board_id, card_id, checklist_id) REFERENCES checklists(board_id, card_id, id) ON DELETE RESTRICT\n"
");\n";
static const char migration_v4[] =
"CREATE INDEX checklist_items_card_order_idx ON checklist_items(card_id, checklist_id, position, id);\n";
static const char migration_v5[] =
"CREATE TABLE labels (\n"
"  board_id TEXT NOT NULL CHECK (typeof(board_id) = 'text' AND length(CAST(board_id AS BLOB)) BETWEEN 1 AND 64 AND instr(board_id, char(0)) = 0),\n"
"  id TEXT NOT NULL CHECK (typeof(id) = 'text' AND length(CAST(id AS BLOB)) BETWEEN 1 AND 64 AND instr(id, char(0)) = 0),\n"
"  name TEXT NOT NULL DEFAULT '' CHECK (typeof(name) = 'text' AND length(CAST(name AS BLOB)) <= 128 AND instr(name, char(0)) = 0),\n"
"  color TEXT NOT NULL DEFAULT '' CHECK (typeof(color) = 'text' AND instr(color, char(0)) = 0 AND (color IN ('', 'white', 'green', 'yellow', 'orange', 'red', 'purple', 'blue', 'sky', 'lime', 'pink', 'black', 'silver', 'peachpuff', 'crimson', 'plum', 'darkgreen', 'slateblue', 'magenta', 'gold', 'navy', 'gray', 'saddlebrown', 'paleturquoise', 'mistyrose', 'indigo') OR (length(CAST(color AS BLOB)) = 7 AND substr(color, 1, 1) = '#' AND substr(color, 2) NOT GLOB '*[^0-9a-fA-F]*'))),\n"
"  position INTEGER NOT NULL CHECK (typeof(position) = 'integer' AND position BETWEEN 0 AND 2147483647),\n"
"  version INTEGER NOT NULL DEFAULT 1 CHECK (typeof(version) = 'integer' AND version > 0),\n"
"  created_at INTEGER NOT NULL DEFAULT 0 CHECK (typeof(created_at) = 'integer' AND created_at >= 0),\n"
"  updated_at INTEGER NOT NULL DEFAULT 0 CHECK (typeof(updated_at) = 'integer' AND updated_at >= created_at),\n"
"  PRIMARY KEY (board_id, id),\n"
"  UNIQUE (board_id, position),\n"
"  UNIQUE (board_id, name, color),\n"
"  FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE RESTRICT\n"
");\n"
"CREATE TABLE card_labels (\n"
"  board_id TEXT NOT NULL CHECK (typeof(board_id) = 'text' AND length(CAST(board_id AS BLOB)) BETWEEN 1 AND 64 AND instr(board_id, char(0)) = 0),\n"
"  card_id TEXT NOT NULL CHECK (typeof(card_id) = 'text' AND length(CAST(card_id AS BLOB)) BETWEEN 1 AND 64 AND instr(card_id, char(0)) = 0),\n"
"  label_id TEXT NOT NULL CHECK (typeof(label_id) = 'text' AND length(CAST(label_id AS BLOB)) BETWEEN 1 AND 64 AND instr(label_id, char(0)) = 0),\n"
"  PRIMARY KEY (board_id, card_id, label_id),\n"
"  FOREIGN KEY (board_id, card_id) REFERENCES cards(board_id, id) ON DELETE RESTRICT,\n"
"  FOREIGN KEY (board_id, label_id) REFERENCES labels(board_id, id) ON DELETE RESTRICT\n"
");\n"
"CREATE INDEX card_labels_label_cards_idx ON card_labels(board_id, label_id, card_id);\n"
"CREATE INDEX card_labels_card_order_idx ON card_labels(card_id, label_id, board_id);\n";
static const char migration_v6[] =
"CREATE TABLE board_settings (\n"
"  board_id TEXT NOT NULL PRIMARY KEY CHECK (typeof(board_id) = 'text' AND length(CAST(board_id AS BLOB)) BETWEEN 1 AND 64 AND instr(board_id, char(0)) = 0),\n"
"  show_checklist_count INTEGER NOT NULL DEFAULT 0 CHECK (typeof(show_checklist_count) = 'integer' AND show_checklist_count IN (0, 1)),\n"
"  FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE RESTRICT\n"
");\n";
static const char migration_v7[] =
"CREATE TABLE board_minicard_settings (\n"
"  board_id TEXT NOT NULL PRIMARY KEY CHECK (typeof(board_id) = 'text' AND length(CAST(board_id AS BLOB)) BETWEEN 1 AND 64 AND instr(board_id, char(0)) = 0),\n"
"  show_checklists INTEGER NOT NULL DEFAULT 1 CHECK (typeof(show_checklists) = 'integer' AND show_checklists IN (0, 1)),\n"
"  FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE RESTRICT\n"
");\n";
static const char migration_v8[] =
"CREATE TABLE actor_card_sections (\n"
"  actor_id TEXT NOT NULL CHECK (typeof(actor_id) = 'text' AND length(CAST(actor_id AS BLOB)) BETWEEN 1 AND 64 AND instr(actor_id, char(0)) = 0),\n"
"  card_id TEXT NOT NULL CHECK (typeof(card_id) = 'text' AND length(CAST(card_id AS BLOB)) BETWEEN 1 AND 64 AND instr(card_id, char(0)) = 0),\n"
"  section_key TEXT NOT NULL CHECK (typeof(section_key) = 'text' AND length(CAST(section_key AS BLOB)) BETWEEN 1 AND 128 AND instr(section_key, char(0)) = 0),\n"
"  collapsed INTEGER NOT NULL CHECK (typeof(collapsed) = 'integer' AND collapsed IN (0, 1)),\n"
"  version INTEGER NOT NULL DEFAULT 1 CHECK (typeof(version) = 'integer' AND version > 0),\n"
"  PRIMARY KEY (actor_id, card_id, section_key),\n"
"  FOREIGN KEY (actor_id) REFERENCES actors(id) ON DELETE RESTRICT,\n"
"  FOREIGN KEY (card_id) REFERENCES cards(id) ON DELETE RESTRICT\n"
");\n";
static const char migration_v9[] =
"CREATE TABLE board_card_collapse_settings (\n"
"  board_id TEXT NOT NULL PRIMARY KEY CHECK (typeof(board_id) = 'text' AND length(CAST(board_id AS BLOB)) BETWEEN 1 AND 64 AND instr(board_id, char(0)) = 0),\n"
"  allow_collapse INTEGER NOT NULL DEFAULT 1 CHECK (typeof(allow_collapse) = 'integer' AND allow_collapse IN (0, 1)),\n"
"  FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE RESTRICT\n"
");\n";
static const char migration_v10[] =
"CREATE TABLE list_archive_state (\n"
"  list_id TEXT NOT NULL PRIMARY KEY CHECK (typeof(list_id) = 'text' AND length(CAST(list_id AS BLOB)) BETWEEN 1 AND 64 AND instr(list_id, char(0)) = 0),\n"
"  board_id TEXT NOT NULL CHECK (typeof(board_id) = 'text' AND length(CAST(board_id AS BLOB)) BETWEEN 1 AND 64 AND instr(board_id, char(0)) = 0),\n"
"  archived INTEGER NOT NULL DEFAULT 0 CHECK (typeof(archived) = 'integer' AND archived IN (0, 1)),\n"
"  archived_at INTEGER NOT NULL DEFAULT 0 CHECK (typeof(archived_at) = 'integer' AND archived_at >= 0),\n"
"  FOREIGN KEY (board_id, list_id) REFERENCES lists(board_id, id) ON DELETE RESTRICT\n"
");\n"
"CREATE INDEX list_archive_board_idx ON list_archive_state(board_id, archived, list_id);\n";
static const char migration_v11[] =
"CREATE TABLE list_colors (\n"
"  list_id TEXT NOT NULL PRIMARY KEY CHECK (typeof(list_id) = 'text' AND length(CAST(list_id AS BLOB)) BETWEEN 1 AND 64 AND instr(list_id, char(0)) = 0),\n"
"  board_id TEXT NOT NULL CHECK (typeof(board_id) = 'text' AND length(CAST(board_id AS BLOB)) BETWEEN 1 AND 64 AND instr(board_id, char(0)) = 0),\n"
"  color TEXT NOT NULL DEFAULT '' CHECK (typeof(color) = 'text' AND instr(color, char(0)) = 0 AND (color IN ('', 'white', 'green', 'yellow', 'orange', 'red', 'purple', 'blue', 'sky', 'lime', 'pink', 'black', 'silver', 'peachpuff', 'crimson', 'plum', 'darkgreen', 'slateblue', 'magenta', 'gold', 'navy', 'gray', 'saddlebrown', 'paleturquoise', 'mistyrose', 'indigo') OR (length(CAST(color AS BLOB)) = 7 AND substr(color, 1, 1) = '#' AND substr(color, 2) NOT GLOB '*[^0-9a-fA-F]*'))),\n"
"  FOREIGN KEY (board_id, list_id) REFERENCES lists(board_id, id) ON DELETE RESTRICT\n"
");\n"
"CREATE INDEX list_colors_board_idx ON list_colors(board_id, list_id);\n"
"CREATE TABLE swimlane_colors (\n"
"  swimlane_id TEXT NOT NULL PRIMARY KEY CHECK (typeof(swimlane_id) = 'text' AND length(CAST(swimlane_id AS BLOB)) BETWEEN 1 AND 64 AND instr(swimlane_id, char(0)) = 0),\n"
"  board_id TEXT NOT NULL CHECK (typeof(board_id) = 'text' AND length(CAST(board_id AS BLOB)) BETWEEN 1 AND 64 AND instr(board_id, char(0)) = 0),\n"
"  color TEXT NOT NULL DEFAULT '' CHECK (typeof(color) = 'text' AND instr(color, char(0)) = 0 AND (color IN ('', 'white', 'green', 'yellow', 'orange', 'red', 'purple', 'blue', 'sky', 'lime', 'pink', 'black', 'silver', 'peachpuff', 'crimson', 'plum', 'darkgreen', 'slateblue', 'magenta', 'gold', 'navy', 'gray', 'saddlebrown', 'paleturquoise', 'mistyrose', 'indigo') OR (length(CAST(color AS BLOB)) = 7 AND substr(color, 1, 1) = '#' AND substr(color, 2) NOT GLOB '*[^0-9a-fA-F]*'))),\n"
"  FOREIGN KEY (board_id, swimlane_id) REFERENCES swimlanes(board_id, id) ON DELETE RESTRICT\n"
");\n"
"CREATE INDEX swimlane_colors_board_idx ON swimlane_colors(board_id, swimlane_id);\n";
static const WenaCompiledMigration migrations[] = {
    {1, migration_v1, 2249u, "e4760a2b70d6651ee84dce93642ccdd4ce8991b488dece5d231e66053f065da5", 2249u, "e4760a2b70d6651ee84dce93642ccdd4ce8991b488dece5d231e66053f065da5"},
    {2, migration_v2, 424u, "429503c784a355f492d4ca6e65428a5e38375ec9d04fc63d264a9ffe1cf6ad83", 2673u, "0653cc5cce0527d8ed5b4f10e184f82b0636d4aee83a5ca27914db7f8f8d7919"},
    {3, migration_v3, 2313u, "944b67e3548c07694a86f630fa3acd0d61bd298e8df5c648d9bb2d7da6fc886c", 4986u, "80a19517e0633f8f1445e136c6560c2e2f88b6349b0d2d99f1146433f9a9d704"},
    {4, migration_v4, 101u, "0d3dd3c932a4c710fdba04b3d7eda22efaa2693a411369d2cdc6368b8898606c", 5087u, "5f315dcf32ce637ebbc147d1cc2522e6ec214fa6a2c32f00b797fec9183c4427"},
    {5, migration_v5, 2315u, "ed5db1279fac66f43648bd6a309335cf272e7b4b868b6ea950252ab1e5304317", 7402u, "460dd2311693546f8624f168b2fb16bd4b5b18fd9b6922a2469759d840a47a81"},
    {6, migration_v6, 391u, "d4d89950ca938a52ff238ef57b44ee6bc54996c7361a45a1d519183acb3c50ed", 7793u, "3d688bc7af1ec04eef142ac3e50522a0dd4acac1328b38067d19b05909fe3d3a"},
    {7, migration_v7, 385u, "e67771f1a9b59a15e3681a003db247919c26b9fef4c92a4ecf8dae5a8dd29a86", 8178u, "ea8829086b29ec811f546d128589d363fe337729506de0dedcd304a8b35e0681"},
    {8, migration_v8, 843u, "20d32a701cd08e370fd45afda40b1bf3db278feda0266f91546071b175d58cd4", 9021u, "23278383993f7a5b1fe4d0cef413c7a8bcee31e93c18b93c1d2572fc69f5df09"},
    {9, migration_v9, 387u, "e69c2dd37a03beb1c404223e212abe920fa88b9f5aad9fa561ae01ac4a4b6e7d", 9408u, "d33b785da15b151791ec33f7bd4516e3cb82b471fcf5ed943d08b59d10c9b09a"},
    {10, migration_v10, 709u, "569f851244e439b5106cf081ad43a07fb026eed894bef133368ba7cda48bcc1d", 10117u, "36eb52ba96835f1612b8de1175acd83a03c6f92df0576161ff683455a2924373"},
    {11, migration_v11, 1968u, "9c5a04b32f44bd3327ea08ee4ac21b6ba14c7d28aba3a77ebbf6e09f99146070", 12085u, "c9d3a3c589cd906396377433356dc52a67ac69e6fe7201d3eadb17fd4280576b"},
};
static const WenaSchemaObject schema_objects[] = {
    {2, "cards_board_id_unique", "index", "CREATE UNIQUE INDEX cards_board_id_unique ON cards(board_id, id)"},
    {2, "card_descriptions", "table", "CREATE TABLE card_descriptions (\n  card_id TEXT NOT NULL PRIMARY KEY,\n  board_id TEXT NOT NULL,\n  description TEXT NOT NULL DEFAULT '' CHECK (\n    typeof(description) = 'text' AND\n    length(CAST(description AS BLOB)) <= 1024 AND\n    instr(description, char(0)) = 0\n  ),\n  FOREIGN KEY (board_id, card_id) REFERENCES cards(board_id, id) ON DELETE RESTRICT\n)"},
    {3, "checklists", "table", "CREATE TABLE checklists (\n  id TEXT NOT NULL PRIMARY KEY CHECK (typeof(id) = 'text' AND length(CAST(id AS BLOB)) BETWEEN 1 AND 64 AND instr(id, char(0)) = 0),\n  board_id TEXT NOT NULL,\n  card_id TEXT NOT NULL,\n  title TEXT NOT NULL CHECK (typeof(title) = 'text' AND length(CAST(title AS BLOB)) BETWEEN 1 AND 128 AND instr(title, char(0)) = 0),\n  position INTEGER NOT NULL CHECK (typeof(position) = 'integer' AND position BETWEEN 0 AND 2147483647),\n  hide_checked_items INTEGER NOT NULL DEFAULT 0 CHECK (typeof(hide_checked_items) = 'integer' AND hide_checked_items IN (0, 1)),\n  hide_all_items INTEGER NOT NULL DEFAULT 0 CHECK (typeof(hide_all_items) = 'integer' AND hide_all_items IN (0, 1)),\n  show_on_minicard INTEGER DEFAULT NULL CHECK (show_on_minicard IS NULL OR (typeof(show_on_minicard) = 'integer' AND show_on_minicard IN (0, 1))),\n  version INTEGER NOT NULL DEFAULT 1 CHECK (typeof(version) = 'integer' AND version > 0),\n  created_at INTEGER NOT NULL DEFAULT 0 CHECK (typeof(created_at) = 'integer' AND created_at >= 0),\n  updated_at INTEGER NOT NULL DEFAULT 0 CHECK (typeof(updated_at) = 'integer' AND updated_at >= 0),\n  UNIQUE (board_id, card_id, id),\n  UNIQUE (card_id, position),\n  FOREIGN KEY (board_id, card_id) REFERENCES cards(board_id, id) ON DELETE RESTRICT\n)"},
    {3, "checklist_items", "table", "CREATE TABLE checklist_items (\n  id TEXT NOT NULL PRIMARY KEY CHECK (typeof(id) = 'text' AND length(CAST(id AS BLOB)) BETWEEN 1 AND 64 AND instr(id, char(0)) = 0),\n  board_id TEXT NOT NULL,\n  card_id TEXT NOT NULL,\n  checklist_id TEXT NOT NULL,\n  title TEXT NOT NULL CHECK (typeof(title) = 'text' AND length(CAST(title AS BLOB)) BETWEEN 1 AND 128 AND instr(title, char(0)) = 0),\n  position INTEGER NOT NULL CHECK (typeof(position) = 'integer' AND position BETWEEN 0 AND 2147483647),\n  is_finished INTEGER NOT NULL DEFAULT 0 CHECK (typeof(is_finished) = 'integer' AND is_finished IN (0, 1)),\n  version INTEGER NOT NULL DEFAULT 1 CHECK (typeof(version) = 'integer' AND version > 0),\n  created_at INTEGER NOT NULL DEFAULT 0 CHECK (typeof(created_at) = 'integer' AND created_at >= 0),\n  updated_at INTEGER NOT NULL DEFAULT 0 CHECK (typeof(updated_at) = 'integer' AND updated_at >= 0),\n  UNIQUE (checklist_id, position),\n  FOREIGN KEY (board_id, card_id, checklist_id) REFERENCES checklists(board_id, card_id, id) ON DELETE RESTRICT\n)"},
    {4, "checklist_items_card_order_idx", "index", "CREATE INDEX checklist_items_card_order_idx ON checklist_items(card_id, checklist_id, position, id)"},
    {5, "labels", "table", "CREATE TABLE labels (\n  board_id TEXT NOT NULL CHECK (typeof(board_id) = 'text' AND length(CAST(board_id AS BLOB)) BETWEEN 1 AND 64 AND instr(board_id, char(0)) = 0),\n  id TEXT NOT NULL CHECK (typeof(id) = 'text' AND length(CAST(id AS BLOB)) BETWEEN 1 AND 64 AND instr(id, char(0)) = 0),\n  name TEXT NOT NULL DEFAULT '' CHECK (typeof(name) = 'text' AND length(CAST(name AS BLOB)) <= 128 AND instr(name, char(0)) = 0),\n  color TEXT NOT NULL DEFAULT '' CHECK (typeof(color) = 'text' AND instr(color, char(0)) = 0 AND (color IN ('', 'white', 'green', 'yellow', 'orange', 'red', 'purple', 'blue', 'sky', 'lime', 'pink', 'black', 'silver', 'peachpuff', 'crimson', 'plum', 'darkgreen', 'slateblue', 'magenta', 'gold', 'navy', 'gray', 'saddlebrown', 'paleturquoise', 'mistyrose', 'indigo') OR (length(CAST(color AS BLOB)) = 7 AND substr(color, 1, 1) = '#' AND substr(color, 2) NOT GLOB '*[^0-9a-fA-F]*'))),\n  position INTEGER NOT NULL CHECK (typeof(position) = 'integer' AND position BETWEEN 0 AND 2147483647),\n  version INTEGER NOT NULL DEFAULT 1 CHECK (typeof(version) = 'integer' AND version > 0),\n  created_at INTEGER NOT NULL DEFAULT 0 CHECK (typeof(created_at) = 'integer' AND created_at >= 0),\n  updated_at INTEGER NOT NULL DEFAULT 0 CHECK (typeof(updated_at) = 'integer' AND updated_at >= created_at),\n  PRIMARY KEY (board_id, id),\n  UNIQUE (board_id, position),\n  UNIQUE (board_id, name, color),\n  FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE RESTRICT\n)"},
    {5, "card_labels", "table", "CREATE TABLE card_labels (\n  board_id TEXT NOT NULL CHECK (typeof(board_id) = 'text' AND length(CAST(board_id AS BLOB)) BETWEEN 1 AND 64 AND instr(board_id, char(0)) = 0),\n  card_id TEXT NOT NULL CHECK (typeof(card_id) = 'text' AND length(CAST(card_id AS BLOB)) BETWEEN 1 AND 64 AND instr(card_id, char(0)) = 0),\n  label_id TEXT NOT NULL CHECK (typeof(label_id) = 'text' AND length(CAST(label_id AS BLOB)) BETWEEN 1 AND 64 AND instr(label_id, char(0)) = 0),\n  PRIMARY KEY (board_id, card_id, label_id),\n  FOREIGN KEY (board_id, card_id) REFERENCES cards(board_id, id) ON DELETE RESTRICT,\n  FOREIGN KEY (board_id, label_id) REFERENCES labels(board_id, id) ON DELETE RESTRICT\n)"},
    {5, "card_labels_label_cards_idx", "index", "CREATE INDEX card_labels_label_cards_idx ON card_labels(board_id, label_id, card_id)"},
    {5, "card_labels_card_order_idx", "index", "CREATE INDEX card_labels_card_order_idx ON card_labels(card_id, label_id, board_id)"},
    {6, "board_settings", "table", "CREATE TABLE board_settings (\n  board_id TEXT NOT NULL PRIMARY KEY CHECK (typeof(board_id) = 'text' AND length(CAST(board_id AS BLOB)) BETWEEN 1 AND 64 AND instr(board_id, char(0)) = 0),\n  show_checklist_count INTEGER NOT NULL DEFAULT 0 CHECK (typeof(show_checklist_count) = 'integer' AND show_checklist_count IN (0, 1)),\n  FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE RESTRICT\n)"},
    {7, "board_minicard_settings", "table", "CREATE TABLE board_minicard_settings (\n  board_id TEXT NOT NULL PRIMARY KEY CHECK (typeof(board_id) = 'text' AND length(CAST(board_id AS BLOB)) BETWEEN 1 AND 64 AND instr(board_id, char(0)) = 0),\n  show_checklists INTEGER NOT NULL DEFAULT 1 CHECK (typeof(show_checklists) = 'integer' AND show_checklists IN (0, 1)),\n  FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE RESTRICT\n)"},
    {8, "actor_card_sections", "table", "CREATE TABLE actor_card_sections (\n  actor_id TEXT NOT NULL CHECK (typeof(actor_id) = 'text' AND length(CAST(actor_id AS BLOB)) BETWEEN 1 AND 64 AND instr(actor_id, char(0)) = 0),\n  card_id TEXT NOT NULL CHECK (typeof(card_id) = 'text' AND length(CAST(card_id AS BLOB)) BETWEEN 1 AND 64 AND instr(card_id, char(0)) = 0),\n  section_key TEXT NOT NULL CHECK (typeof(section_key) = 'text' AND length(CAST(section_key AS BLOB)) BETWEEN 1 AND 128 AND instr(section_key, char(0)) = 0),\n  collapsed INTEGER NOT NULL CHECK (typeof(collapsed) = 'integer' AND collapsed IN (0, 1)),\n  version INTEGER NOT NULL DEFAULT 1 CHECK (typeof(version) = 'integer' AND version > 0),\n  PRIMARY KEY (actor_id, card_id, section_key),\n  FOREIGN KEY (actor_id) REFERENCES actors(id) ON DELETE RESTRICT,\n  FOREIGN KEY (card_id) REFERENCES cards(id) ON DELETE RESTRICT\n)"},
    {9, "board_card_collapse_settings", "table", "CREATE TABLE board_card_collapse_settings (\n  board_id TEXT NOT NULL PRIMARY KEY CHECK (typeof(board_id) = 'text' AND length(CAST(board_id AS BLOB)) BETWEEN 1 AND 64 AND instr(board_id, char(0)) = 0),\n  allow_collapse INTEGER NOT NULL DEFAULT 1 CHECK (typeof(allow_collapse) = 'integer' AND allow_collapse IN (0, 1)),\n  FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE RESTRICT\n)"},
    {10, "list_archive_state", "table", "CREATE TABLE list_archive_state (\n  list_id TEXT NOT NULL PRIMARY KEY CHECK (typeof(list_id) = 'text' AND length(CAST(list_id AS BLOB)) BETWEEN 1 AND 64 AND instr(list_id, char(0)) = 0),\n  board_id TEXT NOT NULL CHECK (typeof(board_id) = 'text' AND length(CAST(board_id AS BLOB)) BETWEEN 1 AND 64 AND instr(board_id, char(0)) = 0),\n  archived INTEGER NOT NULL DEFAULT 0 CHECK (typeof(archived) = 'integer' AND archived IN (0, 1)),\n  archived_at INTEGER NOT NULL DEFAULT 0 CHECK (typeof(archived_at) = 'integer' AND archived_at >= 0),\n  FOREIGN KEY (board_id, list_id) REFERENCES lists(board_id, id) ON DELETE RESTRICT\n)"},
    {10, "list_archive_board_idx", "index", "CREATE INDEX list_archive_board_idx ON list_archive_state(board_id, archived, list_id)"},
    {11, "list_colors", "table", "CREATE TABLE list_colors (\n  list_id TEXT NOT NULL PRIMARY KEY CHECK (typeof(list_id) = 'text' AND length(CAST(list_id AS BLOB)) BETWEEN 1 AND 64 AND instr(list_id, char(0)) = 0),\n  board_id TEXT NOT NULL CHECK (typeof(board_id) = 'text' AND length(CAST(board_id AS BLOB)) BETWEEN 1 AND 64 AND instr(board_id, char(0)) = 0),\n  color TEXT NOT NULL DEFAULT '' CHECK (typeof(color) = 'text' AND instr(color, char(0)) = 0 AND (color IN ('', 'white', 'green', 'yellow', 'orange', 'red', 'purple', 'blue', 'sky', 'lime', 'pink', 'black', 'silver', 'peachpuff', 'crimson', 'plum', 'darkgreen', 'slateblue', 'magenta', 'gold', 'navy', 'gray', 'saddlebrown', 'paleturquoise', 'mistyrose', 'indigo') OR (length(CAST(color AS BLOB)) = 7 AND substr(color, 1, 1) = '#' AND substr(color, 2) NOT GLOB '*[^0-9a-fA-F]*'))),\n  FOREIGN KEY (board_id, list_id) REFERENCES lists(board_id, id) ON DELETE RESTRICT\n)"},
    {11, "list_colors_board_idx", "index", "CREATE INDEX list_colors_board_idx ON list_colors(board_id, list_id)"},
    {11, "swimlane_colors", "table", "CREATE TABLE swimlane_colors (\n  swimlane_id TEXT NOT NULL PRIMARY KEY CHECK (typeof(swimlane_id) = 'text' AND length(CAST(swimlane_id AS BLOB)) BETWEEN 1 AND 64 AND instr(swimlane_id, char(0)) = 0),\n  board_id TEXT NOT NULL CHECK (typeof(board_id) = 'text' AND length(CAST(board_id AS BLOB)) BETWEEN 1 AND 64 AND instr(board_id, char(0)) = 0),\n  color TEXT NOT NULL DEFAULT '' CHECK (typeof(color) = 'text' AND instr(color, char(0)) = 0 AND (color IN ('', 'white', 'green', 'yellow', 'orange', 'red', 'purple', 'blue', 'sky', 'lime', 'pink', 'black', 'silver', 'peachpuff', 'crimson', 'plum', 'darkgreen', 'slateblue', 'magenta', 'gold', 'navy', 'gray', 'saddlebrown', 'paleturquoise', 'mistyrose', 'indigo') OR (length(CAST(color AS BLOB)) = 7 AND substr(color, 1, 1) = '#' AND substr(color, 2) NOT GLOB '*[^0-9a-fA-F]*'))),\n  FOREIGN KEY (board_id, swimlane_id) REFERENCES swimlanes(board_id, id) ON DELETE RESTRICT\n)"},
    {11, "swimlane_colors_board_idx", "index", "CREATE INDEX swimlane_colors_board_idx ON swimlane_colors(board_id, swimlane_id)"},
};
#if defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
